<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook 02 — Exploratory Data Analysis – Credit Risk and Dollarization in Cambodia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-665a47377fd1fb2966ef7e6e7341ee54.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Credit Risk and Dollarization in Cambodia</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./methodology.html"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notebooks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notebooks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notebooks">    
        <li>
    <a class="dropdown-item" href="./01_data_preparation.html">
 <span class="dropdown-text">01 - Data Preparation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_exploratory_analysis.html">
 <span class="dropdown-text">02 - Exploratory Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_parameter_estimation.html">
 <span class="dropdown-text">03 - Parameter Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_cri_computation.html">
 <span class="dropdown-text">04 - CRI Computation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_stress_testing.html">
 <span class="dropdown-text">05 - Stress Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./06_covid_analysis.html">
 <span class="dropdown-text">06 - COVID-19 Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_rolling_window.html">
 <span class="dropdown-text">07 - Rolling Window</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_robustness.html">
 <span class="dropdown-text">08 - Robustness Checks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_regime_switching.html">
 <span class="dropdown-text">09 - Regime Switching</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10_dynamic_threshold.html">
 <span class="dropdown-text">10 - Dynamic Threshold</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./11_implied_pd.html">
 <span class="dropdown-text">11 - Implied Default Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./12_policy_divergence.html">
 <span class="dropdown-text">12 - Policy Divergence</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#credit-risk-and-dollarization-in-cambodia-dual-currency-spread-analysis" id="toc-credit-risk-and-dollarization-in-cambodia-dual-currency-spread-analysis" class="nav-link active" data-scroll-target="#credit-risk-and-dollarization-in-cambodia-dual-currency-spread-analysis">Credit Risk and Dollarization in Cambodia: Dual-Currency Spread Analysis</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">1. Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#interpretation-table-1-full-sample-descriptive-statistics" id="toc-interpretation-table-1-full-sample-descriptive-statistics" class="nav-link" data-scroll-target="#interpretation-table-1-full-sample-descriptive-statistics">Interpretation — Table 1: Full-Sample Descriptive Statistics</a></li>
  <li><a href="#interpretation-table-1b-sub-period-summary-statistics" id="toc-interpretation-table-1b-sub-period-summary-statistics" class="nav-link" data-scroll-target="#interpretation-table-1b-sub-period-summary-statistics">Interpretation — Table 1b: Sub-Period Summary Statistics</a></li>
  </ul></li>
  <li><a href="#normality-tests" id="toc-normality-tests" class="nav-link" data-scroll-target="#normality-tests">2. Normality Tests</a>
  <ul class="collapse">
  <li><a href="#interpretation-normality-tests" id="toc-interpretation-normality-tests" class="nav-link" data-scroll-target="#interpretation-normality-tests">Interpretation — Normality Tests</a></li>
  </ul></li>
  <li><a href="#stationarity-tests-adf" id="toc-stationarity-tests-adf" class="nav-link" data-scroll-target="#stationarity-tests-adf">3. Stationarity Tests (ADF)</a>
  <ul class="collapse">
  <li><a href="#interpretation-adf-stationarity-tests" id="toc-interpretation-adf-stationarity-tests" class="nav-link" data-scroll-target="#interpretation-adf-stationarity-tests">Interpretation — ADF Stationarity Tests</a></li>
  </ul></li>
  <li><a href="#autocorrelation-analysis" id="toc-autocorrelation-analysis" class="nav-link" data-scroll-target="#autocorrelation-analysis">4. Autocorrelation Analysis</a>
  <ul class="collapse">
  <li><a href="#interpretation-acfpacf-analysis" id="toc-interpretation-acfpacf-analysis" class="nav-link" data-scroll-target="#interpretation-acfpacf-analysis">Interpretation — ACF/PACF Analysis</a></li>
  </ul></li>
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">5. Correlation Analysis</a>
  <ul class="collapse">
  <li><a href="#interpretation-correlation-analysis" id="toc-interpretation-correlation-analysis" class="nav-link" data-scroll-target="#interpretation-correlation-analysis">Interpretation — Correlation Analysis</a></li>
  </ul></li>
  <li><a href="#publication-quality-visualizations" id="toc-publication-quality-visualizations" class="nav-link" data-scroll-target="#publication-quality-visualizations">6. Publication-Quality Visualizations</a>
  <ul class="collapse">
  <li><a href="#figure-1-dual-time-series-with-covid-shading" id="toc-figure-1-dual-time-series-with-covid-shading" class="nav-link" data-scroll-target="#figure-1-dual-time-series-with-covid-shading">Figure 1: Dual Time Series with COVID Shading</a></li>
  <li><a href="#interpretation-figure-1-time-series-of-interest-rate-spreads" id="toc-interpretation-figure-1-time-series-of-interest-rate-spreads" class="nav-link" data-scroll-target="#interpretation-figure-1-time-series-of-interest-rate-spreads">Interpretation — Figure 1: Time Series of Interest Rate Spreads</a></li>
  <li><a href="#figure-2-spread-histograms-with-normal-overlay" id="toc-figure-2-spread-histograms-with-normal-overlay" class="nav-link" data-scroll-target="#figure-2-spread-histograms-with-normal-overlay">Figure 2: Spread Histograms with Normal Overlay</a></li>
  <li><a href="#interpretation-figure-2-distribution-histograms" id="toc-interpretation-figure-2-distribution-histograms" class="nav-link" data-scroll-target="#interpretation-figure-2-distribution-histograms">Interpretation — Figure 2: Distribution Histograms</a></li>
  <li><a href="#figure-3-raw-rates-underlying-components" id="toc-figure-3-raw-rates-underlying-components" class="nav-link" data-scroll-target="#figure-3-raw-rates-underlying-components">Figure 3: Raw Rates (Underlying Components)</a></li>
  <li><a href="#interpretation-figure-3-underlying-interest-rates" id="toc-interpretation-figure-3-underlying-interest-rates" class="nav-link" data-scroll-target="#interpretation-figure-3-underlying-interest-rates">Interpretation — Figure 3: Underlying Interest Rates</a></li>
  <li><a href="#figure-4-scatter-plot-usd-vs-khr-spread" id="toc-figure-4-scatter-plot-usd-vs-khr-spread" class="nav-link" data-scroll-target="#figure-4-scatter-plot-usd-vs-khr-spread">Figure 4: Scatter Plot — USD vs KHR Spread</a></li>
  <li><a href="#interpretation-figure-4-cross-currency-scatter-plot" id="toc-interpretation-figure-4-cross-currency-scatter-plot" class="nav-link" data-scroll-target="#interpretation-figure-4-cross-currency-scatter-plot">Interpretation — Figure 4: Cross-Currency Scatter Plot</a></li>
  <li><a href="#figure-5-box-plots-by-year" id="toc-figure-5-box-plots-by-year" class="nav-link" data-scroll-target="#figure-5-box-plots-by-year">Figure 5: Box Plots by Year</a></li>
  <li><a href="#interpretation-figure-5-annual-box-plots" id="toc-interpretation-figure-5-annual-box-plots" class="nav-link" data-scroll-target="#interpretation-figure-5-annual-box-plots">Interpretation — Figure 5: Annual Box Plots</a></li>
  </ul></li>
  <li><a href="#summary-of-key-findings" id="toc-summary-of-key-findings" class="nav-link" data-scroll-target="#summary-of-key-findings">Summary of Key Findings</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Notebook 02 — Exploratory Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="credit-risk-and-dollarization-in-cambodia-dual-currency-spread-analysis" class="level2">
<h2 class="anchored" data-anchor-id="credit-risk-and-dollarization-in-cambodia-dual-currency-spread-analysis">Credit Risk and Dollarization in Cambodia: Dual-Currency Spread Analysis</h2>
<p>This notebook performs comprehensive exploratory analysis of the USD and KHR interest rate spreads (term loan rate − term deposit rate) computed in Notebook 01.</p>
<p><strong>Contents:</strong> 1. Descriptive Statistics (full sample &amp; sub-period) 2. Normality Tests (Shapiro-Wilk, Jarque-Bera) 3. Stationarity Tests (Augmented Dickey-Fuller) 4. Autocorrelation Analysis (ACF/PACF) 5. Correlation Analysis 6. Publication-Quality Visualizations (Figures 1–5)</p>
<div id="cell-2" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Rectangle</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller, acf, pacf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Publication-quality plot settings</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'figure.figsize'</span>: (<span class="dv">12</span>, <span class="dv">6</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'figure.dpi'</span>: <span class="dv">150</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'savefig.dpi'</span>: <span class="dv">300</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'font.size'</span>: <span class="dv">11</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.titlesize'</span>: <span class="dv">14</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'axes.labelsize'</span>: <span class="dv">12</span>,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.fontsize'</span>: <span class="dv">10</span>,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'xtick.labelsize'</span>: <span class="dv">10</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ytick.labelsize'</span>: <span class="dv">10</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'font.family'</span>: <span class="st">'serif'</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Libraries loaded successfully.'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Libraries loaded successfully.</code></pre>
</div>
</div>
<div id="cell-3" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Load Data ───────────────────────────────────────────────────────────────</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>usd <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_usd_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>khr <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_khr_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>rates <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/all_rates_wide_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'Date'</span>], index_col<span class="op">=</span><span class="st">'Date'</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine spreads into a single DataFrame</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>spreads <span class="op">=</span> pd.DataFrame({</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'USD_Spread'</span>: usd[<span class="st">'spread'</span>],</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'KHR_Spread'</span>: khr[<span class="st">'spread'</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Sample period: </span><span class="sc">{</span>spreads<span class="sc">.</span>index[<span class="dv">0</span>]<span class="sc">.</span>strftime(<span class="st">"%b %Y"</span>)<span class="sc">}</span><span class="ss"> – </span><span class="sc">{</span>spreads<span class="sc">.</span>index[<span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span>strftime(<span class="st">"%b %Y"</span>)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Total observations: </span><span class="sc">{</span><span class="bu">len</span>(spreads)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>spreads.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample period: Jan 2013 – Dec 2025
Total observations: 156</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">USD_Spread</th>
<th data-quarto-table-cell-role="th">KHR_Spread</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013-01-01</th>
<td>11.301030</td>
<td>23.535486</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2013-02-01</th>
<td>11.246530</td>
<td>23.732449</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013-03-01</th>
<td>10.856020</td>
<td>23.802566</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2013-04-01</th>
<td>9.653532</td>
<td>24.122855</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2013-05-01</th>
<td>9.296079</td>
<td>23.937022</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">1. Descriptive Statistics</h2>
<div id="cell-5" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Full-Sample Descriptive Statistics ──────────────────────────────────────</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> descriptive_stats(series, name):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Compute comprehensive descriptive statistics for a spread series."""</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series({</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Mean (%)'</span>: series.mean(),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Std. Dev. (%)'</span>: series.std(),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Min (%)'</span>: series.<span class="bu">min</span>(),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Max (%)'</span>: series.<span class="bu">max</span>(),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Median (%)'</span>: series.median(),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Skewness'</span>: series.skew(),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Kurtosis'</span>: series.kurtosis(),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P5 (%)'</span>: series.quantile(<span class="fl">0.05</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P25 (%)'</span>: series.quantile(<span class="fl">0.25</span>),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P50 (%)'</span>: series.quantile(<span class="fl">0.50</span>),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P75 (%)'</span>: series.quantile(<span class="fl">0.75</span>),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'P95 (%)'</span>: series.quantile(<span class="fl">0.95</span>),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">'N'</span>: <span class="bu">len</span>(series)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    }, name<span class="op">=</span>name)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>stats_table <span class="op">=</span> pd.DataFrame([</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    descriptive_stats(spreads[<span class="st">'USD_Spread'</span>], <span class="st">'USD Spread'</span>),</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    descriptive_stats(spreads[<span class="st">'KHR_Spread'</span>], <span class="st">'KHR Spread'</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>]).T</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">══════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'          TABLE 1: Descriptive Statistics — Full Sample'</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'══════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats_table.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'══════════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
══════════════════════════════════════════════════════════════
          TABLE 1: Descriptive Statistics — Full Sample
══════════════════════════════════════════════════════════════
               USD Spread  KHR Spread
Mean (%)           6.7231     11.3415
Std. Dev. (%)      2.0158      7.1069
Min (%)            2.8771      4.2383
Max (%)           11.3010     26.6490
Median (%)         6.0398      6.9478
Skewness           0.7441      0.7615
Kurtosis          -0.4826     -1.1156
P5 (%)             4.2754      4.8265
P25 (%)            5.4318      5.7037
P50 (%)            6.0398      6.9478
P75 (%)            8.2154     19.1597
P95 (%)           10.7268     23.9373
N                156.0000    156.0000
══════════════════════════════════════════════════════════════</code></pre>
</div>
</div>
<section id="interpretation-table-1-full-sample-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-table-1-full-sample-descriptive-statistics">Interpretation — Table 1: Full-Sample Descriptive Statistics</h3>
<p>The descriptive statistics reveal <strong>striking differences</strong> between the two currency segments:</p>
<p><b>1.</b> Level Difference:** The KHR spread averages <strong>11.34%</strong>, nearly <strong>1.7 times</strong> the USD spread average of <strong>6.72%</strong>. This gap reflects the <strong>exchange rate risk premium</strong> embedded in riel-denominated lending — borrowers taking KHR loans face currency depreciation risk, and banks compensate with wider margins. It also captures the less competitive, less mature KHR lending market compared to the deeper, more standardized USD segment.</p>
<p><b>2.</b> Volatility Difference:** KHR spread volatility (std = <strong>7.11%</strong>) is <strong>3.5 times</strong> higher than USD (std = <strong>2.02%</strong>). This is the single most important finding for credit risk: the KHR segment exhibits <strong>substantially more risk instability</strong>. The KHR spread ranges from 4.24% to 26.65% (a 22.4 pp range), versus USD’s 2.88% to 11.30% (an 8.4 pp range).</p>
<p><b>3.</b> Mean vs.&nbsp;Median Divergence:** The KHR median (6.95%) is <strong>far below</strong> its mean (11.34%), indicating the distribution is <strong>heavily right-skewed</strong> — dominated by the early-sample high values when KHR spreads exceeded 20%. By contrast, the USD median (6.04%) is closer to its mean, suggesting a more symmetric distribution around typical values.</p>
<p><b>4.</b> Skewness and Kurtosis:** Both spreads are positively skewed (USD: 0.74, KHR: 0.76), meaning extreme <strong>widenings</strong> are more common than extreme compressions — consistent with credit risk theory where risk materializes through sudden spread blowouts. The negative kurtosis for KHR (−1.12) indicates a <strong>platykurtic</strong> distribution — fat but spread out, without the extreme tails one might expect. This suggests risk in the KHR segment manifests as <strong>sustained elevated spreads</strong> rather than sudden spikes.</p>
<p><b>5.</b> Percentile Analysis:** The 95th percentile values (USD: 10.73%, KHR: 23.94%) will serve as <strong>crisis thresholds</strong> in Notebook 04. When spreads exceed these levels, the CRI will signal elevated credit risk conditions.</p>
<div id="cell-7" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Sub-Period Descriptive Statistics ────────────────────────────────────────</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>periods <span class="op">=</span> {</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Pre-COVID (2013–2019)'</span>: (<span class="st">'2013-01-01'</span>, <span class="st">'2019-12-31'</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'COVID (2020–2021)'</span>:     (<span class="st">'2020-01-01'</span>, <span class="st">'2021-12-31'</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Post-COVID (2022–2025)'</span>:(<span class="st">'2022-01-01'</span>, <span class="st">'2025-12-31'</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>sub_stats <span class="op">=</span> []</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> pname, (start, end) <span class="kw">in</span> periods.items():</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> (spreads.index <span class="op">&gt;=</span> start) <span class="op">&amp;</span> (spreads.index <span class="op">&lt;=</span> end)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> spreads[mask]</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> {</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Period'</span>: pname,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'N'</span>: <span class="bu">len</span>(sub),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'USD Mean (%)'</span>: sub[<span class="st">'USD_Spread'</span>].mean(),</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'USD Std (%)'</span>: sub[<span class="st">'USD_Spread'</span>].std(),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">'KHR Mean (%)'</span>: sub[<span class="st">'KHR_Spread'</span>].mean(),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">'KHR Std (%)'</span>: sub[<span class="st">'KHR_Spread'</span>].std(),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Correlation'</span>: sub[<span class="st">'USD_Spread'</span>].corr(sub[<span class="st">'KHR_Spread'</span>])</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    sub_stats.append(row)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>sub_df <span class="op">=</span> pd.DataFrame(sub_stats).set_index(<span class="st">'Period'</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'         TABLE 1b: Sub-Period Summary Statistics'</span>)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sub_df.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
═══════════════════════════════════════════════════════════════════════
         TABLE 1b: Sub-Period Summary Statistics
═══════════════════════════════════════════════════════════════════════
                         N  USD Mean (%)  USD Std (%)  KHR Mean (%)  KHR Std (%)  Correlation
Period                                                                                       
Pre-COVID (2013–2019)   84        7.9756       1.9105       16.0243       6.7636       0.7264
COVID (2020–2021)       24        5.7721       0.3628        6.1232       0.8247       0.1068
Post-COVID (2022–2025)  48        5.0066       0.7849        5.7559       0.7008       0.4071
═══════════════════════════════════════════════════════════════════════</code></pre>
</div>
</div>
</section>
<section id="interpretation-table-1b-sub-period-summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-table-1b-sub-period-summary-statistics">Interpretation — Table 1b: Sub-Period Summary Statistics</h3>
<p>The sub-period breakdown reveals <strong>dramatic structural shifts</strong> across the three eras:</p>
<p><b>1.</b> KHR Spread Compression — The Dominant Story:<strong> The KHR mean spread </strong>collapsed** from 16.02% (pre-COVID) to 6.12% (COVID) to 5.76% (post-COVID) — a <strong>64% decline</strong> over the sample. This compression reflects the <strong>maturation of Cambodia’s financial sector</strong>: increasing banking competition, improved credit assessment capabilities, NBC’s de-dollarization policies promoting riel lending, and greater confidence in the domestic currency. The KHR volatility similarly plummeted from 6.76% to just 0.82% during COVID and 0.70% post-COVID — the riel market has become <strong>qualitatively different</strong> from 2013 to 2025.</p>
<p><b>2.</b> USD Spread Stability and Compression:<strong> The USD spread also declined but more modestly: from 7.98% (pre-COVID) to 5.77% (COVID) to 5.01% (post-COVID) — a </strong>37% decline<strong>. This reflects global factors (prolonged low interest rate environment 2013–2021) combined with Cambodia-specific banking sector deepening. USD volatility dropped from 1.91% pre-COVID to just 0.36% during COVID, reflecting the </strong>NBC loan restructuring program** that stabilized lending conditions.</p>
<p><b>3.</b> Correlation Breakdown During COVID:<strong> The correlation between USD and KHR spreads </strong>collapsed** from 0.73 (pre-COVID) to just <strong>0.11</strong> during COVID, then partially recovered to 0.41 post-COVID. This is a critical finding: <strong>during the crisis, the two currency segments decoupled</strong>. This means a single-currency credit risk framework would miss important divergent dynamics. It also suggests that COVID-specific policies (NBC restructuring, Fed rate cuts) affected the two segments through different channels — validating the dual-currency approach of this paper.</p>
<p><b>4.</b> Convergence of Spread Levels:<strong> By the post-COVID period, the gap between USD and KHR spreads has narrowed to just ~0.75 pp (5.01% vs 5.76%), compared to ~8.0 pp in the pre-COVID era. This </strong>convergence** is consistent with NBC’s de-dollarization progress — as KHR lending matures, its risk pricing approaches that of the more established USD segment.</p>
<hr>
</section>
</section>
<section id="normality-tests" class="level2">
<h2 class="anchored" data-anchor-id="normality-tests">2. Normality Tests</h2>
<div id="cell-10" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Normality Tests ─────────────────────────────────────────────────────────</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>normality_results <span class="op">=</span> []</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col, label <span class="kw">in</span> [(<span class="st">'USD_Spread'</span>, <span class="st">'USD Spread'</span>), (<span class="st">'KHR_Spread'</span>, <span class="st">'KHR Spread'</span>)]:</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    sw_stat, sw_p <span class="op">=</span> stats.shapiro(spreads[col])</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    jb_stat, jb_p <span class="op">=</span> stats.jarque_bera(spreads[col])</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    normality_results.append({</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Series'</span>: label,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Shapiro-Wilk Stat'</span>: sw_stat,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Shapiro-Wilk p-value'</span>: sw_p,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Jarque-Bera Stat'</span>: jb_stat,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Jarque-Bera p-value'</span>: jb_p,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Normal at 5%?'</span>: <span class="st">'Yes'</span> <span class="cf">if</span> (sw_p <span class="op">&gt;</span> <span class="fl">0.05</span> <span class="kw">and</span> jb_p <span class="op">&gt;</span> <span class="fl">0.05</span>) <span class="cf">else</span> <span class="st">'No'</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>norm_df <span class="op">=</span> pd.DataFrame(normality_results).set_index(<span class="st">'Series'</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'                    Normality Test Results'</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(norm_df.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
═══════════════════════════════════════════════════════════════
                    Normality Test Results
═══════════════════════════════════════════════════════════════
            Shapiro-Wilk Stat  Shapiro-Wilk p-value  Jarque-Bera Stat  Jarque-Bera p-value Normal at 5%?
Series                                                                                                  
USD Spread             0.9113                   0.0           15.7822               0.0004            No
KHR Spread             0.7900                   0.0           22.9171               0.0000            No
═══════════════════════════════════════════════════════════════</code></pre>
</div>
</div>
<section id="interpretation-normality-tests" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-normality-tests">Interpretation — Normality Tests</h3>
<p>Both the Shapiro-Wilk and Jarque-Bera tests <strong>strongly reject normality</strong> for both spread series (p &lt; 0.001 in all cases).</p>
<p><strong>Why this matters:</strong> The OU model assumes normally distributed innovations (the <span class="math inline">\(dW_t\)</span> driving noise). The rejection of unconditional normality does <strong>not</strong> invalidate the OU model — it actually supports it. Here’s why:</p>
<ul>
<li>The <strong>unconditional</strong> distribution of an OU process is only normal if the process is in its stationary regime with constant parameters. Our data spans a period of <strong>major structural change</strong> (KHR spread compressed from 24% to 4%), which creates the right-skewed distribution we observe.</li>
<li>What matters for the OU model is whether the <strong>conditional innovations</strong> (one-step-ahead residuals) are approximately normal. This is tested in Notebook 03’s model diagnostics.</li>
<li>The positive skewness (0.74 for USD, 0.76 for KHR) is consistent with credit risk theory: <strong>spread widenings (risk events) tend to be larger and more sudden than compressions</strong> — a well-documented asymmetry in financial markets.</li>
</ul>
<p><strong>Implication for the paper:</strong> We should mention this non-normality as a known limitation — the OU model captures the mean-reverting dynamics well, but may underestimate tail risks. The stress testing framework in Notebook 05 provides a complementary approach by directly examining how CRI responds to extreme scenarios.</p>
<hr>
</section>
</section>
<section id="stationarity-tests-adf" class="level2">
<h2 class="anchored" data-anchor-id="stationarity-tests-adf">3. Stationarity Tests (ADF)</h2>
<div id="cell-13" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Augmented Dickey-Fuller Tests ───────────────────────────────────────────</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>adf_results <span class="op">=</span> []</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col, label <span class="kw">in</span> [(<span class="st">'USD_Spread'</span>, <span class="st">'USD Spread'</span>), (<span class="st">'KHR_Spread'</span>, <span class="st">'KHR Spread'</span>)]:</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    result <span class="op">=</span> adfuller(spreads[col], autolag<span class="op">=</span><span class="st">'AIC'</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    adf_results.append({</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Series'</span>: label,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'ADF Statistic'</span>: result[<span class="dv">0</span>],</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p-value'</span>: result[<span class="dv">1</span>],</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Lags Used'</span>: result[<span class="dv">2</span>],</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Critical 1%'</span>: result[<span class="dv">4</span>][<span class="st">'1%'</span>],</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Critical 5%'</span>: result[<span class="dv">4</span>][<span class="st">'5%'</span>],</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Critical 10%'</span>: result[<span class="dv">4</span>][<span class="st">'10%'</span>],</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Stationary at 5%?'</span>: <span class="st">'Yes'</span> <span class="cf">if</span> result[<span class="dv">1</span>] <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'No'</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>adf_df <span class="op">=</span> pd.DataFrame(adf_results).set_index(<span class="st">'Series'</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'              Augmented Dickey-Fuller Test Results'</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(adf_df.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
═══════════════════════════════════════════════════════════════════
              Augmented Dickey-Fuller Test Results
═══════════════════════════════════════════════════════════════════
            ADF Statistic  p-value  Lags Used  Critical 1%  Critical 5%  Critical 10% Stationary at 5%?
Series                                                                                                 
USD Spread        -0.6662   0.8553         12      -3.4769      -2.8820       -2.5777                No
KHR Spread        -1.6905   0.4360          3      -3.4741      -2.8807       -2.5770                No
═══════════════════════════════════════════════════════════════════</code></pre>
</div>
</div>
<section id="interpretation-adf-stationarity-tests" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-adf-stationarity-tests">Interpretation — ADF Stationarity Tests</h3>
<p>The ADF test <strong>fails to reject</strong> the unit root null hypothesis for both series: - <strong>USD Spread</strong>: ADF statistic = −0.67, p-value = 0.86 (12 lags selected by AIC) - <strong>KHR Spread</strong>: ADF statistic = −1.69, p-value = 0.44 (3 lags selected)</p>
<p><strong>This is a nuanced but important result.</strong> At first glance, failure to reject a unit root appears to contradict the mean-reverting OU model. However, there are several key reasons why this does NOT invalidate our approach:</p>
<p><b>1.</b> Structural Breaks Reduce ADF Power:<strong> The KHR spread experienced a massive structural compression from ~24% to ~5% over the sample. The ADF test has </strong>well-known low power** in the presence of structural breaks (Perron, 1989). The test interprets the downward trend as evidence of non-stationarity, when in reality the series may be mean-reverting around a <strong>shifting</strong> equilibrium — exactly what our rolling window analysis in Notebook 07 will capture.</p>
<p><b>2.</b> Slow Mean Reversion ≠ Unit Root:<strong> The OU model estimated in Notebook 03 shows KHR has κ = 0.46 (half-life ≈ 18 months). Slow mean reversion is </strong>difficult to distinguish from a unit root** in finite samples — a classic identification problem in financial econometrics (Phillips, 1987). The ADF test lacks the statistical power to distinguish between a near-unit-root process and a slowly mean-reverting one with 156 observations.</p>
<p><b>3.</b> High Lag Selection for USD (12 lags):** The AIC selected 12 lags for the USD spread, consuming degrees of freedom and further reducing test power. This high lag count itself indicates complex serial dependence patterns consistent with a persistent AR process.</p>
<p><b>4.</b> What Supports Mean Reversion Instead:<strong> - Interest rate spreads have a </strong>natural economic floor** (banks cannot sustain negative spreads) and <strong>competitive ceiling</strong> (abnormally high spreads attract new entrants) - The ACF analysis below shows significant but <strong>decaying</strong> autocorrelation — characteristic of mean reversion, not a random walk - The MLE estimation in Notebook 03 confirms positive κ values for both currencies - The sub-period analysis shows spreads <strong>converging</strong> to a new equilibrium rather than wandering unboundedly</p>
<p><strong>For the paper:</strong> We should discuss the ADF results honestly, acknowledge the low power in the presence of structural shifts, and note that the economic argument for mean reversion is strong. The rolling window approach (Notebook 07) addresses this by allowing parameters to vary over time.</p>
<hr>
</section>
</section>
<section id="autocorrelation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="autocorrelation-analysis">4. Autocorrelation Analysis</h2>
<div id="cell-16" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── ACF / PACF Plots ────────────────────────────────────────────────────────</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">8</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plot_acf(spreads[<span class="st">'USD_Spread'</span>], lags<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">0</span>], color<span class="op">=</span><span class="st">'#2196F3'</span>, alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'ACF — USD Spread'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plot_pacf(spreads[<span class="st">'USD_Spread'</span>], lags<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">1</span>], color<span class="op">=</span><span class="st">'#2196F3'</span>, alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">'PACF — USD Spread'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plot_acf(spreads[<span class="st">'KHR_Spread'</span>], lags<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">0</span>], color<span class="op">=</span><span class="st">'#E91E63'</span>, alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'ACF — KHR Spread'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>plot_pacf(spreads[<span class="st">'KHR_Spread'</span>], lags<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">1</span>], color<span class="op">=</span><span class="st">'#E91E63'</span>, alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'PACF — KHR Spread'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes.flat:</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Lag (months)'</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig_acf_pacf.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">AR(1) autocorrelation at lag 1:'</span>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  USD Spread: </span><span class="sc">{</span>spreads[<span class="st">"USD_Spread"</span>]<span class="sc">.</span>autocorr(lag<span class="op">=</span><span class="dv">1</span>)<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  KHR Spread: </span><span class="sc">{</span>spreads[<span class="st">"KHR_Spread"</span>]<span class="sc">.</span>autocorr(lag<span class="op">=</span><span class="dv">1</span>)<span class="sc">:.4f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
AR(1) autocorrelation at lag 1:
  USD Spread: 0.8693
  KHR Spread: 0.9686</code></pre>
</div>
</div>
<section id="interpretation-acfpacf-analysis" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-acfpacf-analysis">Interpretation — ACF/PACF Analysis</h3>
<p>The autocorrelation analysis provides <strong>strong support</strong> for the mean-reverting OU model specification:</p>
<p><b>1.</b> High Lag-1 Autocorrelation:<strong> - </strong>USD Spread<strong>: ρ₁ = </strong>0.87** — strong persistence from one month to the next - <strong>KHR Spread</strong>: ρ₁ = <strong>0.97</strong> — extremely high persistence, nearly a unit root</p>
<p>These values directly map to the OU model: the AR(1) coefficient b = e^(−κΔt), so b = 0.87 implies κ ≈ 1.7 (fast reversion) for USD, while b = 0.97 implies κ ≈ 0.4 (slow reversion) for KHR — consistent with the MLE results in Notebook 03.</p>
<p><b>2.</b> Slowly Decaying ACF Pattern:<strong> Both series show ACF that remains significant for many lags but </strong>gradually decays** — the hallmark of a mean-reverting process. A pure random walk would show ACF near 1.0 at all lags, while white noise would show no significant autocorrelation. The observed pattern is exactly what an OU process produces.</p>
<p><b>3.</b> PACF Drops After Lag 1:<strong> The PACF for both series shows a </strong>dominant spike at lag 1** followed by a rapid drop to near zero. This is the signature of an <strong>AR(1) process</strong> — the discrete-time equivalent of the OU model. There is no evidence of higher-order autoregressive structure (AR(2), AR(3), etc.), confirming that the OU model with three parameters (κ, θ, σ) is an appropriate and parsimonious specification.</p>
<p><b>4.</b> USD vs.&nbsp;KHR Persistence Difference:<strong> The KHR lag-1 autocorrelation of 0.97 (vs.&nbsp;USD’s 0.87) means KHR spread shocks are </strong>much more persistent** — a shock to the KHR spread takes roughly <strong>4x longer</strong> to dissipate than a USD shock. This has direct implications for credit risk: KHR credit conditions, once deteriorated, <strong>remain elevated for much longer</strong>, making the riel segment more vulnerable to prolonged stress periods.</p>
<p><strong>For the paper:</strong> The ACF/PACF evidence provides the <strong>strongest statistical justification</strong> for the OU model choice. We can state that the data are consistent with a first-order autoregressive / mean-reverting process, and that the OU model captures the essential dynamics without over-parameterization.</p>
<hr>
</section>
</section>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">5. Correlation Analysis</h2>
<div id="cell-19" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Correlation Analysis ────────────────────────────────────────────────────</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>full_corr <span class="op">=</span> spreads[<span class="st">'USD_Spread'</span>].corr(spreads[<span class="st">'KHR_Spread'</span>])</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Full-sample Pearson correlation: </span><span class="sc">{</span>full_corr<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Sub-period correlations:'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> pname, (start, end) <span class="kw">in</span> periods.items():</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> (spreads.index <span class="op">&gt;=</span> start) <span class="op">&amp;</span> (spreads.index <span class="op">&lt;=</span> end)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> spreads[mask]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    corr <span class="op">=</span> sub[<span class="st">'USD_Spread'</span>].corr(sub[<span class="st">'KHR_Spread'</span>])</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'  </span><span class="sc">{</span>pname<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>corr<span class="sc">:.4f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full-sample Pearson correlation: 0.8387

Sub-period correlations:
  Pre-COVID (2013–2019): 0.7264
  COVID (2020–2021): 0.1068
  Post-COVID (2022–2025): 0.4071</code></pre>
</div>
</div>
<section id="interpretation-correlation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-correlation-analysis">Interpretation — Correlation Analysis</h3>
<p><strong>Full-Sample Correlation: ρ = 0.84</strong> — USD and KHR spreads are <strong>strongly correlated</strong> but not perfectly so. This dual nature is central to the paper’s contribution:</p>
<ul>
<li>A correlation of 0.84 means the two segments share <strong>common macroeconomic drivers</strong> (GDP growth, global liquidity conditions, banking sector competition), which push both spreads in the same direction</li>
<li>But the remaining 16% unexplained variance reflects <strong>currency-specific factors</strong>: exchange rate risk, NBC policy differences between currencies, and different borrower profiles in each segment</li>
</ul>
<p><strong>The Sub-Period Correlation Story Is Dramatic:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Period</th>
<th style="text-align: center;">Correlation</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-COVID</td>
<td style="text-align: center;">0.73</td>
<td>Strong co-movement in normal times</td>
</tr>
<tr class="even">
<td>COVID</td>
<td style="text-align: center;"><strong>0.11</strong></td>
<td>Near-complete decoupling during crisis</td>
</tr>
<tr class="odd">
<td>Post-COVID</td>
<td style="text-align: center;">0.41</td>
<td>Partial recovery, but weaker than before</td>
</tr>
</tbody>
</table>
<p>The <strong>collapse to 0.11 during COVID</strong> is one of the most important findings for the paper. It means:</p>
<ol type="1">
<li><strong>A single-currency analysis would be deeply misleading</strong> — COVID affected USD and KHR credit risk through entirely different channels</li>
<li>The USD segment was stabilized by <strong>global Fed policy</strong> (emergency rate cuts to 0%), while KHR was influenced by <strong>domestic NBC policies</strong> (loan restructuring program, riel liquidity support)</li>
<li>This <strong>correlation breakdown under stress</strong> is a classic feature of financial crises (see Forbes &amp; Rigobon, 2002) and is exactly why a <strong>dual-currency framework</strong> is necessary</li>
</ol>
<p>The only partial recovery to 0.41 post-COVID suggests the relationship between the two segments may have <strong>permanently shifted</strong> — consistent with the KHR spread’s structural compression to levels similar to USD.</p>
<hr>
</section>
</section>
<section id="publication-quality-visualizations" class="level2">
<h2 class="anchored" data-anchor-id="publication-quality-visualizations">6. Publication-Quality Visualizations</h2>
<section id="figure-1-dual-time-series-with-covid-shading" class="level3">
<h3 class="anchored" data-anchor-id="figure-1-dual-time-series-with-covid-shading">Figure 1: Dual Time Series with COVID Shading</h3>
<div id="cell-22" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── FIGURE 1: Dual Time Series ──────────────────────────────────────────────</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ax.plot(spreads.index, spreads[<span class="st">'USD_Spread'</span>], color<span class="op">=</span><span class="st">'#1565C0'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">'USD Spread'</span>, alpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ax.plot(spreads.index, spreads[<span class="st">'KHR_Spread'</span>], color<span class="op">=</span><span class="st">'#C62828'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">'KHR Spread'</span>, alpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># COVID shading</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>ax.axvspan(pd.Timestamp(<span class="st">'2020-01-01'</span>), pd.Timestamp(<span class="st">'2021-12-31'</span>),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>           alpha<span class="op">=</span><span class="fl">0.12</span>, color<span class="op">=</span><span class="st">'grey'</span>, label<span class="op">=</span><span class="st">'COVID-19 Period'</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Event annotations</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>events <span class="op">=</span> [</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'2020-03-01'</span>, <span class="st">'COVID-19</span><span class="ch">\n</span><span class="st">Onset'</span>, <span class="dv">15</span>),</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'2022-03-01'</span>, <span class="st">'Fed Rate</span><span class="ch">\n</span><span class="st">Hikes Begin'</span>, <span class="dv">18</span>),</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'2023-07-01'</span>, <span class="st">'Fed Peak</span><span class="ch">\n</span><span class="st">Rate'</span>, <span class="dv">15</span>),</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'2024-09-01'</span>, <span class="st">'Fed Rate</span><span class="ch">\n</span><span class="st">Cuts Begin'</span>, <span class="dv">18</span>),</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> date, label, ypos <span class="kw">in</span> events:</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    ax.annotate(label, xy<span class="op">=</span>(pd.Timestamp(date), ypos),</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>                fontsize<span class="op">=</span><span class="fl">7.5</span>, ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>                bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round,pad=0.3'</span>, facecolor<span class="op">=</span><span class="st">'lightyellow'</span>,</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>                          edgecolor<span class="op">=</span><span class="st">'grey'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>),</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>                arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'grey'</span>, lw<span class="op">=</span><span class="fl">0.8</span>))</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Date'</span>)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Interest Rate Spread (%)'</span>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Figure 1: USD and KHR Interest Rate Spreads (Jan 2013 – Dec 2025)'</span>,</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>             fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'upper right'</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(mdates.YearLocator())</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'%Y'</span>))</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig1_spread_timeseries.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig1_spread_timeseries.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved: fig1_spread_timeseries.png</code></pre>
</div>
</div>
</section>
<section id="interpretation-figure-1-time-series-of-interest-rate-spreads" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-figure-1-time-series-of-interest-rate-spreads">Interpretation — Figure 1: Time Series of Interest Rate Spreads</h3>
<p>Figure 1 tells the <strong>central story</strong> of Cambodia’s dual-currency credit risk evolution:</p>
<p><strong>Phase 1 — High KHR Divergence (2013–2016):</strong> The KHR spread fluctuated between 13–27%, dwarfing the USD spread of 5–11%. This massive gap — sometimes exceeding <strong>15 percentage points</strong> — reflects the early-stage KHR lending market, where banks charged enormous risk premiums for riel-denominated loans due to limited riel liquidity, high perceived exchange rate risk, and the dominance of USD in banking.</p>
<p><strong>Phase 2 — KHR Compression (2017–2019):</strong> The KHR spread underwent <strong>rapid compression</strong>, falling from ~15% to ~5%. This coincides with NBC’s active de-dollarization efforts (higher USD reserve requirements, riel lending incentives) and the general maturation of the banking sector. The gap between currencies narrowed dramatically.</p>
<p><strong>Phase 3 — COVID Stability (2020–2021):</strong> Surprisingly, both spreads <strong>remained remarkably stable</strong> during the pandemic, with USD holding at ~5.5% and KHR at ~6%. This reflects the NBC’s aggressive <strong>loan restructuring program</strong> that prevented banks from repricing risk upward — essentially masking underlying credit deterioration.</p>
<p><strong>Phase 4 — Post-COVID Convergence (2022–2025):</strong> Post-COVID, both spreads settled into a narrow 4–7% band, with intermittent volatility linked to the <strong>Fed tightening cycle</strong> (2022–2023). The convergence of USD and KHR spreads to similar levels is historical — by 2025, the centuries-old KHR risk premium has effectively disappeared in the term lending market.</p>
<p><strong>Key Observation:</strong> The anomalous KHR spike to ~27% in January 2017 is a notable outlier — likely a data artifact or a single large transaction distorting the weighted average. This does not invalidate the overall trend.</p>
</section>
<section id="figure-2-spread-histograms-with-normal-overlay" class="level3">
<h3 class="anchored" data-anchor-id="figure-2-spread-histograms-with-normal-overlay">Figure 2: Spread Histograms with Normal Overlay</h3>
<div id="cell-25" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── FIGURE 2: Histograms ────────────────────────────────────────────────────</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, col, color, label <span class="kw">in</span> [(ax1, <span class="st">'USD_Spread'</span>, <span class="st">'#1565C0'</span>, <span class="st">'USD'</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                               (ax2, <span class="st">'KHR_Spread'</span>, <span class="st">'#C62828'</span>, <span class="st">'KHR'</span>)]:</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> spreads[col]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    ax.hist(data, bins<span class="op">=</span><span class="dv">25</span>, density<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Normal overlay</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(data.<span class="bu">min</span>() <span class="op">-</span> <span class="dv">1</span>, data.<span class="bu">max</span>() <span class="op">+</span> <span class="dv">1</span>, <span class="dv">200</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, stats.norm.pdf(x, data.mean(), data.std()),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Normal fit'</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> Spread (%)'</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Density'</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> Spread Distribution'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Stats annotation</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    textstr <span class="op">=</span> <span class="ss">f'μ = </span><span class="sc">{</span>data<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">%</span><span class="ch">\n</span><span class="ss">σ = </span><span class="sc">{</span>data<span class="sc">.</span>std()<span class="sc">:.2f}</span><span class="ss">%</span><span class="ch">\n</span><span class="ss">Skew = </span><span class="sc">{</span>data<span class="sc">.</span>skew()<span class="sc">:.2f}</span><span class="ch">\n</span><span class="ss">Kurt = </span><span class="sc">{</span>data<span class="sc">.</span>kurtosis()<span class="sc">:.2f}</span><span class="ss">'</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    ax.text(<span class="fl">0.97</span>, <span class="fl">0.97</span>, textstr, transform<span class="op">=</span>ax.transAxes, fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>            verticalalignment<span class="op">=</span><span class="st">'top'</span>, horizontalalignment<span class="op">=</span><span class="st">'right'</span>,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>            bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round'</span>, facecolor<span class="op">=</span><span class="st">'wheat'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>))</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Figure 2: Distribution of Interest Rate Spreads'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig2_spread_histograms.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig2_spread_histograms.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved: fig2_spread_histograms.png</code></pre>
</div>
</div>
</section>
<section id="interpretation-figure-2-distribution-histograms" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-figure-2-distribution-histograms">Interpretation — Figure 2: Distribution Histograms</h3>
<p>The histograms visually confirm the non-normality detected by the statistical tests:</p>
<p><strong>USD Spread:</strong> The distribution is <strong>moderately right-skewed</strong> with a concentration of observations between 4–7%. The bulk of the data clusters below the mean of 6.72%, with a long right tail extending to ~11%. This asymmetry arises because the USD spread spent most of the post-2018 period at lower levels (4–6%) but had higher values in the early sample (2013–2016). The normal overlay shows reasonable fit in the center of the distribution but underestimates the right tail — confirming that extreme spread widenings occur more frequently than a normal model predicts.</p>
<p><strong>KHR Spread:</strong> The distribution is <strong>bimodal or heavily skewed</strong> — a large mass of observations at 4–7% (the post-2018 regime) and a wide, flat tail extending to 24–27% (the pre-2018 regime). The normal overlay is a poor fit, vastly underestimating both the left concentration and the right tail. This is a visual representation of the <strong>structural break</strong> — the KHR spread has effectively operated in two distinct regimes. For modeling purposes, this explains why a rolling window approach (Notebook 07) is valuable: parameters estimated on the full sample will be pulled toward a “compromise” that fits neither regime well.</p>
</section>
<section id="figure-3-raw-rates-underlying-components" class="level3">
<h3 class="anchored" data-anchor-id="figure-3-raw-rates-underlying-components">Figure 3: Raw Rates (Underlying Components)</h3>
<div id="cell-28" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── FIGURE 3: Raw Rates ─────────────────────────────────────────────────────</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">9</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># USD rates</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>ax1.plot(rates.index, rates[<span class="st">'USD_Term_Loans'</span>], color<span class="op">=</span><span class="st">'#1565C0'</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'USD Term Loan Rate'</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>ax1.plot(rates.index, rates[<span class="st">'USD_Term_Deposits'</span>], color<span class="op">=</span><span class="st">'#64B5F6'</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'USD Term Deposit Rate'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>ax1.fill_between(rates.index, rates[<span class="st">'USD_Term_Deposits'</span>], rates[<span class="st">'USD_Term_Loans'</span>],</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                 alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span><span class="st">'#1565C0'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>ax1.axvspan(pd.Timestamp(<span class="st">'2020-01-01'</span>), pd.Timestamp(<span class="st">'2021-12-31'</span>),</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Rate (%)'</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'USD — Term Loan and Term Deposit Rates'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>ax1.legend(loc<span class="op">=</span><span class="st">'upper right'</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="co"># KHR rates</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>ax2.plot(rates.index, rates[<span class="st">'KHR_Term_Loans'</span>], color<span class="op">=</span><span class="st">'#C62828'</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>,</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'KHR Term Loan Rate'</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>ax2.plot(rates.index, rates[<span class="st">'KHR_Term_Deposits'</span>], color<span class="op">=</span><span class="st">'#EF9A9A'</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'KHR Term Deposit Rate'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>ax2.fill_between(rates.index, rates[<span class="st">'KHR_Term_Deposits'</span>], rates[<span class="st">'KHR_Term_Loans'</span>],</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>                 alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span><span class="st">'#C62828'</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>ax2.axvspan(pd.Timestamp(<span class="st">'2020-01-01'</span>), pd.Timestamp(<span class="st">'2021-12-31'</span>),</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>            alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Date'</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Rate (%)'</span>)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'KHR — Term Loan and Term Deposit Rates'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>ax2.legend(loc<span class="op">=</span><span class="st">'upper right'</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>ax2.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>ax2.xaxis.set_major_locator(mdates.YearLocator())</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>ax2.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'%Y'</span>))</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Figure 3: Underlying Interest Rates — New Amount (Jan 2013 – Dec 2025)'</span>,</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>             fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, y<span class="op">=</span><span class="fl">1.01</span>)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig3_raw_rates.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig3_raw_rates.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved: fig3_raw_rates.png</code></pre>
</div>
</div>
</section>
<section id="interpretation-figure-3-underlying-interest-rates" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-figure-3-underlying-interest-rates">Interpretation — Figure 3: Underlying Interest Rates</h3>
<p>This figure reveals <strong>what drives the spreads</strong> by decomposing them into their lending and deposit rate components:</p>
<p><strong>USD Panel — Two Distinct Regimes:</strong> - <strong>2013–2019:</strong> USD loan rates declined from ~14% to ~9% while deposit rates remained stable at ~3.3%. The narrowing spread was driven <strong>entirely by loan rate compression</strong> — increasing banking competition in the dominant USD lending market. - <strong>2022–2025:</strong> Deposit rates <strong>surged</strong> from ~3.5% to ~5.5% due to the Fed’s aggressive tightening cycle (0% → 5.25%). This represents a transmission of U.S. monetary policy into Cambodia’s dollarized economy — Cambodian banks had to raise USD deposit rates to remain competitive with rising global rates. Loan rates also ticked up modestly, but the net effect was <strong>spread compression</strong> to the 3–6% range.</p>
<p><strong>KHR Panel — Dramatic Loan Rate Collapse:</strong> - KHR loan rates halved from ~30% (2013) to ~10–12% (2019–2025), the single largest change in the dataset. This reflects banking sector maturation, increased competition in the riel segment, NBC incentives for riel lending, and the general development of Cambodia’s financial infrastructure. - KHR deposit rates remained relatively stable at 5–7% throughout, slightly higher than USD deposits — reflecting the premium banks offer to attract riel deposits. - The spread compression was therefore driven <strong>almost entirely by declining loan rates</strong>, not by rising deposit rates. This is a sign of <strong>healthy financial development</strong> — borrowers accessing credit at lower cost.</p>
<p><strong>Key Insight for the Paper:</strong> The USD spread is increasingly influenced by <strong>external factors</strong> (Fed policy), while the KHR spread is driven by <strong>domestic structural changes</strong> (financial deepening, de-dollarization). This divergence in drivers explains the COVID-era correlation breakdown and supports modeling each currency separately.</p>
</section>
<section id="figure-4-scatter-plot-usd-vs-khr-spread" class="level3">
<h3 class="anchored" data-anchor-id="figure-4-scatter-plot-usd-vs-khr-spread">Figure 4: Scatter Plot — USD vs KHR Spread</h3>
<div id="cell-31" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── FIGURE 4: Scatter Plot ──────────────────────────────────────────────────</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Color by period</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> []</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> d <span class="kw">in</span> spreads.index:</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> d <span class="op">&lt;</span> pd.Timestamp(<span class="st">'2020-01-01'</span>):</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>        colors.append(<span class="st">'#1565C0'</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> d <span class="op">&lt;</span> pd.Timestamp(<span class="st">'2022-01-01'</span>):</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>        colors.append(<span class="st">'#FF6F00'</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>        colors.append(<span class="st">'#2E7D32'</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>scatter <span class="op">=</span> ax.scatter(spreads[<span class="st">'USD_Spread'</span>], spreads[<span class="st">'KHR_Spread'</span>],</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>                     c<span class="op">=</span>colors, alpha<span class="op">=</span><span class="fl">0.6</span>, s<span class="op">=</span><span class="dv">40</span>, edgecolors<span class="op">=</span><span class="st">'white'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression line</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>slope, intercept, r_value, p_value, std_err <span class="op">=</span> stats.linregress(</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    spreads[<span class="st">'USD_Spread'</span>], spreads[<span class="st">'KHR_Spread'</span>])</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>x_line <span class="op">=</span> np.linspace(spreads[<span class="st">'USD_Spread'</span>].<span class="bu">min</span>(), spreads[<span class="st">'USD_Spread'</span>].<span class="bu">max</span>(), <span class="dv">100</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>ax.plot(x_line, slope <span class="op">*</span> x_line <span class="op">+</span> intercept, <span class="st">'k--'</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Legend</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.lines <span class="im">import</span> Line2D</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>legend_elements <span class="op">=</span> [</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>    Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">'w'</span>, markerfacecolor<span class="op">=</span><span class="st">'#1565C0'</span>, markersize<span class="op">=</span><span class="dv">8</span>, label<span class="op">=</span><span class="st">'Pre-COVID'</span>),</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>    Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">'w'</span>, markerfacecolor<span class="op">=</span><span class="st">'#FF6F00'</span>, markersize<span class="op">=</span><span class="dv">8</span>, label<span class="op">=</span><span class="st">'COVID'</span>),</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>    Line2D([<span class="dv">0</span>], [<span class="dv">0</span>], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">'w'</span>, markerfacecolor<span class="op">=</span><span class="st">'#2E7D32'</span>, markersize<span class="op">=</span><span class="dv">8</span>, label<span class="op">=</span><span class="st">'Post-COVID'</span>),</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>ax.legend(handles<span class="op">=</span>legend_elements, loc<span class="op">=</span><span class="st">'upper right'</span>)</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'USD Spread (%)'</span>)</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'KHR Spread (%)'</span>)</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Figure 4: USD vs. KHR Spread Correlation'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.05</span>, <span class="fl">0.95</span>, <span class="ss">f'ρ = </span><span class="sc">{</span>r_value<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">p &lt; 0.0001'</span>,</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>        transform<span class="op">=</span>ax.transAxes, fontsize<span class="op">=</span><span class="dv">11</span>, verticalalignment<span class="op">=</span><span class="st">'top'</span>,</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>        bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round'</span>, facecolor<span class="op">=</span><span class="st">'lightyellow'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>))</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig4_correlation.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig4_correlation.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved: fig4_correlation.png</code></pre>
</div>
</div>
</section>
<section id="interpretation-figure-4-cross-currency-scatter-plot" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-figure-4-cross-currency-scatter-plot">Interpretation — Figure 4: Cross-Currency Scatter Plot</h3>
<p>The scatter plot beautifully illustrates the <strong>time-varying relationship</strong> between the two currency segments:</p>
<p><strong>Three Distinct Clusters Emerge:</strong></p>
<ol type="1">
<li><p><strong>Pre-COVID (blue)</strong> — Occupies the upper-right region with a clear positive slope. When USD spreads were high (7–11%), KHR spreads were extremely high (12–26%). The wide dispersion of blue points reflects the volatile KHR market of 2013–2017.</p></li>
<li><p><strong>COVID (orange)</strong> — A compact cluster in the lower-left, around USD 5–6% and KHR 5–7%. The tight clustering reflects the <strong>artificially stabilized</strong> market during the NBC restructuring period. These 24 points are nearly independent of each other (correlation ≈ 0.11), appearing as a <strong>random scatter</strong> within the cluster.</p></li>
<li><p><strong>Post-COVID (green)</strong> — Concentrated in the lower-left at USD 3.5–6.5% and KHR 4.5–7%. Very similar to the COVID cluster but with slightly more spread, reflecting the <strong>new normal</strong> of converged dual-currency pricing.</p></li>
</ol>
<p><strong>The regression line (ρ = 0.84)</strong> captures the overall positive relationship, but the visual clearly shows this is driven by the <strong>cross-period variation</strong> (the shift from upper-right to lower-left) rather than within-period co-movement. This is a classic example of how a high correlation can be misleading when driven by a common trend rather than genuine short-term co-movement — further supporting the dual-currency modeling approach.</p>
</section>
<section id="figure-5-box-plots-by-year" class="level3">
<h3 class="anchored" data-anchor-id="figure-5-box-plots-by-year">Figure 5: Box Plots by Year</h3>
<div id="cell-34" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── FIGURE 5: Box Plots by Year ─────────────────────────────────────────────</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>spreads_year <span class="op">=</span> spreads.copy()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>spreads_year[<span class="st">'Year'</span>] <span class="op">=</span> spreads_year.index.year</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">8</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>years <span class="op">=</span> <span class="bu">sorted</span>(spreads_year[<span class="st">'Year'</span>].unique())</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>usd_by_year <span class="op">=</span> [spreads_year[spreads_year[<span class="st">'Year'</span>]<span class="op">==</span>y][<span class="st">'USD_Spread'</span>].values <span class="cf">for</span> y <span class="kw">in</span> years]</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>khr_by_year <span class="op">=</span> [spreads_year[spreads_year[<span class="st">'Year'</span>]<span class="op">==</span>y][<span class="st">'KHR_Spread'</span>].values <span class="cf">for</span> y <span class="kw">in</span> years]</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>bp1 <span class="op">=</span> ax1.boxplot(usd_by_year, labels<span class="op">=</span>years, patch_artist<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> box <span class="kw">in</span> bp1[<span class="st">'boxes'</span>]:</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    box.<span class="bu">set</span>(facecolor<span class="op">=</span><span class="st">'#BBDEFB'</span>, edgecolor<span class="op">=</span><span class="st">'#1565C0'</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Spread (%)'</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'USD Spread Distribution by Year'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade COVID years</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> [ax1, ax2]:</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>    covid_start_idx <span class="op">=</span> years.index(<span class="dv">2020</span>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>    ax.axvspan(covid_start_idx <span class="op">+</span> <span class="fl">0.5</span>, covid_start_idx <span class="op">+</span> <span class="fl">2.5</span>, alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>bp2 <span class="op">=</span> ax2.boxplot(khr_by_year, labels<span class="op">=</span>years, patch_artist<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> box <span class="kw">in</span> bp2[<span class="st">'boxes'</span>]:</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>    box.<span class="bu">set</span>(facecolor<span class="op">=</span><span class="st">'#FFCDD2'</span>, edgecolor<span class="op">=</span><span class="st">'#C62828'</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Year'</span>)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Spread (%)'</span>)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'KHR Spread Distribution by Year'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>ax2.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Figure 5: Annual Spread Distributions'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, y<span class="op">=</span><span class="fl">1.01</span>)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig5_boxplots_by_year.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig5_boxplots_by_year.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_exploratory_analysis_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved: fig5_boxplots_by_year.png</code></pre>
</div>
</div>
</section>
<section id="interpretation-figure-5-annual-box-plots" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-figure-5-annual-box-plots">Interpretation — Figure 5: Annual Box Plots</h3>
<p>The box plots provide a year-by-year view of the <strong>distributional evolution</strong>:</p>
<p><strong>USD Spread:</strong> - 2013–2016: High median (~8–10%) with wide boxes, indicating both high levels and high within-year volatility - 2017–2019: Gradual compression to ~6%, boxes narrowing (more stable pricing) - 2020–2021 (COVID, shaded): <strong>Remarkably narrow boxes</strong> centered at ~5.5–5.7% — the restructuring program effectively <strong>froze</strong> risk repricing - 2022–2023: The impact of the Fed tightening cycle is visible in the compressed spreads (3–5%), as rising deposit rates ate into margins - 2024–2025: Partial recovery to 4.5–6% as Fed began cutting rates</p>
<p><strong>KHR Spread:</strong> - 2013–2016: Extremely high medians (18–24%) with large boxes — the immature KHR lending market - 2017: A <strong>dramatic outlier</strong> (Jan 2017 spike to 26.6%) visible as a whisker; excluding this, the median dropped to ~12% - 2018–2019: Rapid compression to 6–8%, boxes much narrower - 2020–2025: Stable at 5–7% with very tight boxes — the KHR market has matured</p>
<p><strong>Key Pattern — Volatility Compression:</strong> Both currencies show a secular trend toward <strong>tighter boxes</strong> (lower within-year volatility) over time. This suggests that Cambodia’s banking sector has become more efficient at pricing credit risk, with less month-to-month fluctuation. For the OU model, this implies that the volatility parameter σ should be <strong>lower in recent sub-periods</strong> — as confirmed in Notebook 06’s COVID analysis.</p>
<hr>
</section>
</section>
<section id="summary-of-key-findings" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-key-findings">Summary of Key Findings</h2>
<p>The exploratory analysis reveals five fundamental characteristics of Cambodia’s dual-currency credit risk landscape:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Finding</th>
<th>USD</th>
<th>KHR</th>
<th>Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean spread</td>
<td>6.72%</td>
<td>11.34%</td>
<td>KHR carries exchange rate risk premium</td>
</tr>
<tr class="even">
<td>Volatility</td>
<td>2.02%</td>
<td>7.11% (3.5× higher)</td>
<td>KHR segment far more unstable</td>
</tr>
<tr class="odd">
<td>Normality</td>
<td>Rejected</td>
<td>Rejected</td>
<td>Stress testing needed for tail risks</td>
</tr>
<tr class="even">
<td>ADF stationarity</td>
<td>Not rejected (p=0.86)</td>
<td>Not rejected (p=0.44)</td>
<td>Structural breaks reduce ADF power</td>
</tr>
<tr class="odd">
<td>Lag-1 autocorrelation</td>
<td>0.87</td>
<td>0.97</td>
<td>KHR shocks much more persistent</td>
</tr>
<tr class="even">
<td>Cross-correlation</td>
<td>0.84 full-sample, <strong>0.11 during COVID</strong></td>
<td></td>
<td>Dual-currency framework essential</td>
</tr>
</tbody>
</table>
<p>These findings validate the choice of the Ornstein-Uhlenbeck stochastic process for modeling, while highlighting that a <strong>time-varying parameter approach</strong> (rolling windows) will be essential to capture the structural shifts in the KHR market. The COVID-era correlation breakdown provides the strongest justification for the paper’s dual-currency framework.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>