<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook 03 — Parameter Estimation – Credit Risk and Dollarization in Cambodia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-665a47377fd1fb2966ef7e6e7341ee54.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Credit Risk and Dollarization in Cambodia</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./methodology.html"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notebooks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notebooks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notebooks">    
        <li>
    <a class="dropdown-item" href="./nb01_data_preparation.html">
 <span class="dropdown-text">01 - Data Preparation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb02_exploratory_analysis.html">
 <span class="dropdown-text">02 - Exploratory Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb03_parameter_estimation.html">
 <span class="dropdown-text">03 - Parameter Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb04_cri_computation.html">
 <span class="dropdown-text">04 - CRI Computation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb05_stress_testing.html">
 <span class="dropdown-text">05 - Stress Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb06_covid_analysis.html">
 <span class="dropdown-text">06 - COVID-19 Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb07_rolling_window.html">
 <span class="dropdown-text">07 - Rolling Window</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb08_robustness.html">
 <span class="dropdown-text">08 - Robustness Checks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb09_regime_switching.html">
 <span class="dropdown-text">09 - Regime Switching</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb10_dynamic_threshold.html">
 <span class="dropdown-text">10 - Dynamic Threshold</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb11_implied_pd.html">
 <span class="dropdown-text">11 - Implied Default Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb12_policy_divergence.html">
 <span class="dropdown-text">12 - Policy Divergence</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#ornstein-uhlenbeck-model-calibration-via-maximum-likelihood" id="toc-ornstein-uhlenbeck-model-calibration-via-maximum-likelihood" class="nav-link active" data-scroll-target="#ornstein-uhlenbeck-model-calibration-via-maximum-likelihood">Ornstein-Uhlenbeck Model Calibration via Maximum Likelihood</a></li>
  <li><a href="#maximum-likelihood-estimation" id="toc-maximum-likelihood-estimation" class="nav-link" data-scroll-target="#maximum-likelihood-estimation">1. Maximum Likelihood Estimation</a>
  <ul class="collapse">
  <li><a href="#interpretation-mle-results-table-2" id="toc-interpretation-mle-results-table-2" class="nav-link" data-scroll-target="#interpretation-mle-results-table-2">Interpretation — MLE Results (Table 2)</a></li>
  <li><a href="#why-ornstein-uhlenbeck-instead-of-cox-ingersoll-ross" id="toc-why-ornstein-uhlenbeck-instead-of-cox-ingersoll-ross" class="nav-link" data-scroll-target="#why-ornstein-uhlenbeck-instead-of-cox-ingersoll-ross">Why Ornstein-Uhlenbeck Instead of Cox-Ingersoll-Ross?</a></li>
  <li><a href="#exact-discrete-time-solution-not-euler-maruyama" id="toc-exact-discrete-time-solution-not-euler-maruyama" class="nav-link" data-scroll-target="#exact-discrete-time-solution-not-euler-maruyama">Exact Discrete-Time Solution (Not Euler-Maruyama)</a></li>
  </ul></li>
  <li><a href="#ar1-cross-check" id="toc-ar1-cross-check" class="nav-link" data-scroll-target="#ar1-cross-check">2. AR(1) Cross-Check</a>
  <ul class="collapse">
  <li><a href="#interpretation-ar1-cross-check" id="toc-interpretation-ar1-cross-check" class="nav-link" data-scroll-target="#interpretation-ar1-cross-check">Interpretation — AR(1) Cross-Check</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">3. Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#interpretation-confidence-intervals" id="toc-interpretation-confidence-intervals" class="nav-link" data-scroll-target="#interpretation-confidence-intervals">Interpretation — Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">4. Model Diagnostics</a>
  <ul class="collapse">
  <li><a href="#interpretation-model-diagnostics-figure-5" id="toc-interpretation-model-diagnostics-figure-5" class="nav-link" data-scroll-target="#interpretation-model-diagnostics-figure-5">Interpretation — Model Diagnostics (Figure 5)</a></li>
  </ul></li>
  <li><a href="#save-parameters-for-downstream-notebooks" id="toc-save-parameters-for-downstream-notebooks" class="nav-link" data-scroll-target="#save-parameters-for-downstream-notebooks">5. Save Parameters for Downstream Notebooks</a></li>
  <li><a href="#summary-of-key-findings" id="toc-summary-of-key-findings" class="nav-link" data-scroll-target="#summary-of-key-findings">Summary of Key Findings</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Notebook 03 — Parameter Estimation</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="ornstein-uhlenbeck-model-calibration-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="ornstein-uhlenbeck-model-calibration-via-maximum-likelihood">Ornstein-Uhlenbeck Model Calibration via Maximum Likelihood</h2>
<p>This notebook estimates the parameters of the OU stochastic differential equation:</p>
<p><span class="math display">\[dS_t^c = \kappa^c(\theta^c - S_t^c)dt + \sigma^c dW_t^c\]</span></p>
<p>where <span class="math inline">\(c \in \{\text{USD}, \text{KHR}\}\)</span>, using maximum likelihood estimation (MLE) and an AR(1) OLS cross-check.</p>
<p><strong>Contents:</strong> 1. MLE for OU Parameters (κ, θ, σ) with standard errors 2. AR(1) Cross-Check 3. Confidence Intervals &amp; Half-Lives 4. Model Diagnostics 5. Parameter Export for Downstream Use</p>
<div id="c8070529" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'figure.figsize'</span>: (<span class="dv">12</span>, <span class="dv">6</span>), <span class="st">'figure.dpi'</span>: <span class="dv">150</span>, <span class="st">'savefig.dpi'</span>: <span class="dv">300</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'font.size'</span>: <span class="dv">11</span>, <span class="st">'axes.titlesize'</span>: <span class="dv">14</span>, <span class="st">'axes.labelsize'</span>: <span class="dv">12</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.fontsize'</span>: <span class="dv">10</span>, <span class="st">'font.family'</span>: <span class="st">'serif'</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Libraries loaded.'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="6ab1ac50" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Load Data ───────────────────────────────────────────────────────────────</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>usd <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_usd_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>khr <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_khr_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>S_usd <span class="op">=</span> usd[<span class="st">'spread'</span>].values</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>S_khr <span class="op">=</span> khr[<span class="st">'spread'</span>].values</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> usd.index</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> <span class="dv">1</span><span class="op">/</span><span class="dv">12</span>  <span class="co"># monthly data → annual time units</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'USD: </span><span class="sc">{</span><span class="bu">len</span>(S_usd)<span class="sc">}</span><span class="ss"> observations, range [</span><span class="sc">{</span>S_usd<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">%, </span><span class="sc">{</span>S_usd<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">%]'</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'KHR: </span><span class="sc">{</span><span class="bu">len</span>(S_khr)<span class="sc">}</span><span class="ss"> observations, range [</span><span class="sc">{</span>S_khr<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">%, </span><span class="sc">{</span>S_khr<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">%]'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="maximum-likelihood-estimation" class="level2">
<h2 class="anchored" data-anchor-id="maximum-likelihood-estimation">1. Maximum Likelihood Estimation</h2>
<p>The exact transition density of the OU process gives:</p>
<p><span class="math display">\[S_{t+\Delta t} | S_t \sim \mathcal{N}\left(\theta + (S_t - \theta)e^{-\kappa\Delta t},\; \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})\right)\]</span></p>
<p>We maximize the resulting log-likelihood over (κ, θ, σ).</p>
<div id="a1558dbb" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── OU Negative Log-Likelihood ──────────────────────────────────────────────</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ou_neg_log_likelihood(params, data, dt):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Exact negative log-likelihood for the OU process."""</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    kappa, theta, sigma <span class="op">=</span> params</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> kappa <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> sigma <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e10</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(data) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    exp_kdt <span class="op">=</span> np.exp(<span class="op">-</span>kappa <span class="op">*</span> dt)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> theta <span class="op">+</span> (data[:<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> theta) <span class="op">*</span> exp_kdt  <span class="co"># conditional means</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> (sigma<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> kappa)) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> kappa <span class="op">*</span> dt))  <span class="co"># conditional variance</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> v <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e10</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    residuals <span class="op">=</span> data[<span class="dv">1</span>:] <span class="op">-</span> m</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(v) <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> np.<span class="bu">sum</span>(residuals<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> v</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>ll</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_ou_mle(data, dt, label<span class="op">=</span><span class="st">''</span>):</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimate OU parameters via MLE with multiple starting points."""</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    theta0 <span class="op">=</span> np.mean(data)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    sigma0 <span class="op">=</span> np.std(np.diff(data)) <span class="op">*</span> np.sqrt(<span class="dv">12</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    best_result <span class="op">=</span> <span class="va">None</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    best_nll <span class="op">=</span> np.inf</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k0 <span class="kw">in</span> [<span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">10.0</span>]:</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>        x0 <span class="op">=</span> [k0, theta0, sigma0]</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> minimize(</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>            ou_neg_log_likelihood, x0, args<span class="op">=</span>(data, dt),</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>            method<span class="op">=</span><span class="st">'Nelder-Mead'</span>,</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>            options<span class="op">=</span>{<span class="st">'maxiter'</span>: <span class="dv">50000</span>, <span class="st">'xatol'</span>: <span class="fl">1e-10</span>, <span class="st">'fatol'</span>: <span class="fl">1e-10</span>}</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> result.fun <span class="op">&lt;</span> best_nll <span class="kw">and</span> result.x[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> result.x[<span class="dv">2</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>            best_nll <span class="op">=</span> result.fun</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>            best_result <span class="op">=</span> result</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    kappa_hat, theta_hat, sigma_hat <span class="op">=</span> best_result.x</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Standard errors via numerical Hessian</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    eps <span class="op">=</span> <span class="fl">1e-5</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    n_params <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    hessian <span class="op">=</span> np.zeros((n_params, n_params))</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>            x_pp <span class="op">=</span> best_result.x.copy()<span class="op">;</span> x_pm <span class="op">=</span> best_result.x.copy()</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>            x_mp <span class="op">=</span> best_result.x.copy()<span class="op">;</span> x_mm <span class="op">=</span> best_result.x.copy()</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>            x_pp[i] <span class="op">+=</span> eps<span class="op">;</span> x_pp[j] <span class="op">+=</span> eps</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>            x_pm[i] <span class="op">+=</span> eps<span class="op">;</span> x_pm[j] <span class="op">-=</span> eps</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>            x_mp[i] <span class="op">-=</span> eps<span class="op">;</span> x_mp[j] <span class="op">+=</span> eps</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>            x_mm[i] <span class="op">-=</span> eps<span class="op">;</span> x_mm[j] <span class="op">-=</span> eps</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>            hessian[i, j] <span class="op">=</span> (</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>                ou_neg_log_likelihood(x_pp, data, dt)</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>                <span class="op">-</span> ou_neg_log_likelihood(x_pm, data, dt)</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>                <span class="op">-</span> ou_neg_log_likelihood(x_mp, data, dt)</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>                <span class="op">+</span> ou_neg_log_likelihood(x_mm, data, dt)</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>            ) <span class="op">/</span> (<span class="dv">4</span> <span class="op">*</span> eps<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>        cov_matrix <span class="op">=</span> np.linalg.inv(hessian)</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> np.sqrt(np.<span class="bu">abs</span>(np.diag(cov_matrix)))</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> np.linalg.LinAlgError:</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> np.array([np.nan, np.nan, np.nan])</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>    half_life <span class="op">=</span> np.log(<span class="dv">2</span>) <span class="op">/</span> kappa_hat</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>    half_life_months <span class="op">=</span> half_life <span class="op">*</span> <span class="dv">12</span></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> {</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>        <span class="st">'kappa'</span>: kappa_hat, <span class="st">'theta'</span>: theta_hat, <span class="st">'sigma'</span>: sigma_hat,</span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>        <span class="st">'se_kappa'</span>: se[<span class="dv">0</span>], <span class="st">'se_theta'</span>: se[<span class="dv">1</span>], <span class="st">'se_sigma'</span>: se[<span class="dv">2</span>],</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>        <span class="st">'log_likelihood'</span>: <span class="op">-</span>best_nll,</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>        <span class="st">'half_life_years'</span>: half_life, <span class="st">'half_life_months'</span>: half_life_months,</span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>        <span class="st">'n_obs'</span>: <span class="bu">len</span>(data)</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label:</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  MLE Results — </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  κ (mean reversion speed) = </span><span class="sc">{</span>kappa_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  θ (long-run mean, %)     = </span><span class="sc">{</span>theta_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  σ (volatility)           = </span><span class="sc">{</span>sigma_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">2</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Half-life                = </span><span class="sc">{</span>half_life_months<span class="sc">:10.2f}</span><span class="ss"> months (</span><span class="sc">{</span>half_life<span class="sc">:.2f}</span><span class="ss"> years)'</span>)</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Log-likelihood           = </span><span class="sc">{</span><span class="op">-</span>best_nll<span class="sc">:10.4f}</span><span class="ss">'</span>)</span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Observations             = </span><span class="sc">{</span><span class="bu">len</span>(data)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> results</span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate for both currencies</span></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>mle_usd <span class="op">=</span> estimate_ou_mle(S_usd, dt, <span class="st">'USD Spread'</span>)</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>mle_khr <span class="op">=</span> estimate_ou_mle(S_khr, dt, <span class="st">'KHR Spread'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="interpretation-mle-results-table-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-mle-results-table-2">Interpretation — MLE Results (Table 2)</h3>
<p>The MLE estimation reveals <strong>fundamentally different credit risk dynamics</strong> in the two currency segments:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 30%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: center;">USD</th>
<th style="text-align: center;">KHR</th>
<th style="text-align: center;">Ratio (KHR/USD)</th>
<th>Economic Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>κ (mean reversion)</td>
<td style="text-align: center;"><strong>1.85</strong></td>
<td style="text-align: center;"><strong>0.46</strong></td>
<td style="text-align: center;">0.25×</td>
<td>KHR reverts <strong>4x slower</strong></td>
</tr>
<tr class="even">
<td>θ (equilibrium, %)</td>
<td style="text-align: center;"><strong>6.44</strong></td>
<td style="text-align: center;"><strong>8.07</strong></td>
<td style="text-align: center;">1.25×</td>
<td>KHR equilibrium <strong>1.6 pp higher</strong></td>
</tr>
<tr class="odd">
<td>σ (volatility)</td>
<td style="text-align: center;"><strong>3.66</strong></td>
<td style="text-align: center;"><strong>6.18</strong></td>
<td style="text-align: center;">1.69×</td>
<td>KHR <strong>1.7x more volatile</strong></td>
</tr>
<tr class="even">
<td>Half-life (months)</td>
<td style="text-align: center;"><strong>4.5</strong></td>
<td style="text-align: center;"><strong>18.1</strong></td>
<td style="text-align: center;">4.0×</td>
<td>KHR shocks <strong>last 4x longer</strong></td>
</tr>
</tbody>
</table>
<p><strong>1. Mean Reversion Speed (κ):</strong> The USD κ = 1.85 (SE = 0.55) is <strong>statistically significant</strong> — the USD spread is pulled back toward equilibrium relatively quickly. After a 1 pp shock, 50% of the deviation dissipates within <strong>4.5 months</strong>. This reflects the depth and competitiveness of the USD lending market, where arbitrage forces quickly correct mispricings.</p>
<p>The KHR κ = 0.46 (SE = 0.25) is lower but still positive, confirming mean reversion exists. However, the half-life of <strong>18 months</strong> means shocks are extremely persistent — it takes a year and a half for half the impact to dissipate. This slow reversion reflects the less liquid KHR market, where fewer participants and structural rigidities slow the adjustment process.</p>
<p><strong>2. Long-Run Equilibrium (θ):</strong> The KHR equilibrium spread (8.07%) exceeds the USD (6.44%) by 1.6 pp.&nbsp;This gap reflects an <strong>exchange rate risk premium</strong> — banks demand a higher margin on riel loans to compensate for potential KHR depreciation against the USD. Importantly, the massive KHR spread compression from ~24% to ~5% is <strong>not purely a reduction in credit risk</strong>; it also captures the evaporation of this FX risk premium as public confidence in the riel grew and the NBC stabilized the exchange rate through reserve management and de-dollarization incentives. Note that the KHR SE for θ (4.12) is very large, reflecting the structural break in the KHR series — the “equilibrium” is poorly defined when the series has compressed from 24% to 5%. This motivates the rolling window analysis in Notebook 07.</p>
<p><strong>3. Volatility (σ):</strong> KHR volatility (6.18) is 1.7× higher than USD (3.66), confirming the KHR segment is <strong>inherently riskier</strong>. Combined with the slower mean reversion, this creates a dangerous combination: when KHR spreads widen, they widen by <strong>more</strong> and stay elevated for <strong>longer</strong>.</p>
<p><strong>4. Stationary Variance:</strong> The unconditional variance of the OU process is σ²/(2κ). For USD: 3.66²/(2×1.85) = <strong>3.62</strong>. For KHR: 6.18²/(2×0.46) = <strong>41.5</strong> — the KHR stationary variance is <strong>11.5 times</strong> the USD value. This quantifies the dramatically different risk profiles.</p>
</section>
<section id="why-ornstein-uhlenbeck-instead-of-cox-ingersoll-ross" class="level3">
<h3 class="anchored" data-anchor-id="why-ornstein-uhlenbeck-instead-of-cox-ingersoll-ross">Why Ornstein-Uhlenbeck Instead of Cox-Ingersoll-Ross?</h3>
<p>An interviewer may ask why we chose the OU process over the <strong>Cox-Ingersoll-Ross (CIR)</strong> model, which scales volatility with the spread level and prevents negative values:</p>
<p><span class="math display">\[dS_t = \kappa(\theta - S_t)\,dt + \sigma\sqrt{S_t}\,dW_t \quad \text{(CIR)}\]</span></p>
<p><strong>Our defense for choosing OU:</strong></p>
<ol type="1">
<li><p><strong>Tractable MLE:</strong> The OU process has an exact Gaussian transition density, giving a clean, globally convex log-likelihood that <code>scipy.optimize.minimize</code> handles reliably. The CIR exact transition density is a <strong>non-central chi-squared</strong> distribution, whose log-likelihood involves Bessel functions and is numerically unstable near certain parameter boundaries — convergence failures and local optima are common.</p></li>
<li><p><strong>Negative values are not a practical concern:</strong> The OU model theoretically permits negative spreads, but our data never approaches zero (USD minimum = 2.88%, KHR minimum = 4.24%). Over the 156-month sample, the OU model places negligible probability mass on negative spreads given the estimated parameters.</p></li>
<li><p><strong>Diagnostics support the choice:</strong> The standardized residuals from the OU fit (Figure 5) are approximately standard normal for USD and reasonable for KHR. If CIR’s <span class="math inline">\(\sqrt{S_t}\)</span> scaling were essential, we would see systematic residual patterns correlated with the spread level — our diagnostics do not show this for USD (though KHR shows some heteroskedasticity related to the structural break, not the level).</p></li>
<li><p><strong>Precedent:</strong> The OU/Vasicek (1977) framework is the standard in the interest rate modeling literature for mean-reverting processes. The CIR extension is typically motivated for short-rate models where rates can approach zero, which is not the case for lending-deposit spreads.</p></li>
</ol>
<p><strong>Bottom line:</strong> We chose analytical tractability over theoretical elegance. The CIR model’s additional complexity does not provide meaningful benefit for this dataset.</p>
</section>
<section id="exact-discrete-time-solution-not-euler-maruyama" class="level3">
<h3 class="anchored" data-anchor-id="exact-discrete-time-solution-not-euler-maruyama">Exact Discrete-Time Solution (Not Euler-Maruyama)</h3>
<p><strong>Important technical note:</strong> Throughout this project, all discrete-time representations use the <strong>exact solution</strong> to the OU SDE, not the Euler-Maruyama approximation. The exact solution is:</p>
<p><span class="math display">\[S_{t+\Delta t} = S_t e^{-\kappa \Delta t} + \theta(1 - e^{-\kappa \Delta t}) + \sigma \sqrt{\frac{1 - e^{-2\kappa \Delta t}}{2\kappa}}\, Z\]</span></p>
<p>where <span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span> and <span class="math inline">\(\Delta t = 1/12\)</span> for monthly data.</p>
<p>This means: - <strong>Conditional mean:</strong> <span class="math inline">\(\mathbb{E}[S_{t+\Delta t} | S_t] = \theta + (S_t - \theta)e^{-\kappa\Delta t}\)</span> — used in our MLE and for the AR(1) mapping below - <strong>Conditional variance:</strong> <span class="math inline">\(\text{Var}(S_{t+\Delta t} | S_t) = \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})\)</span> — used in our MLE log-likelihood</p>
<p>The simpler Euler-Maruyama discretization (<span class="math inline">\(S_{t+\Delta t} \approx S_t + \kappa(\theta - S_t)\Delta t + \sigma\sqrt{\Delta t}\, Z\)</span>) introduces <span class="math inline">\(O(\Delta t)\)</span> bias in parameter estimates. With monthly data (<span class="math inline">\(\Delta t = 1/12\)</span>), this bias can be non-negligible — the exact solution eliminates it entirely.</p>
<p>The AR(1) cross-check below maps <span class="math inline">\(S_{t+1} = a + bS_t + \varepsilon_t\)</span> back to OU parameters using the exact relationships: <span class="math inline">\(b = e^{-\kappa\Delta t}\)</span>, <span class="math inline">\(a = \theta(1-b)\)</span>, confirming consistency with the MLE estimates.</p>
<hr>
</section>
</section>
<section id="ar1-cross-check" class="level2">
<h2 class="anchored" data-anchor-id="ar1-cross-check">2. AR(1) Cross-Check</h2>
<div id="76d3022b" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── AR(1) Cross-Check ───────────────────────────────────────────────────────</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_ou_ar1(data, dt, label<span class="op">=</span><span class="st">''</span>):</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimate OU parameters via AR(1) regression."""</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    S_t <span class="op">=</span> data[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    S_t1 <span class="op">=</span> data[<span class="dv">1</span>:]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    slope, intercept, r_value, p_value, std_err <span class="op">=</span> stats.linregress(S_t, S_t1)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    b_hat <span class="op">=</span> slope</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    a_hat <span class="op">=</span> intercept</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    residuals <span class="op">=</span> S_t1 <span class="op">-</span> (a_hat <span class="op">+</span> b_hat <span class="op">*</span> S_t)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    sigma_eps <span class="op">=</span> residuals.std()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> b_hat <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> b_hat <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        kappa_hat <span class="op">=</span> <span class="op">-</span>np.log(b_hat) <span class="op">/</span> dt</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        theta_hat <span class="op">=</span> a_hat <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> b_hat)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        sigma_hat <span class="op">=</span> sigma_eps <span class="op">*</span> np.sqrt(<span class="dv">2</span> <span class="op">*</span> kappa_hat <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> b_hat<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        kappa_hat <span class="op">=</span> theta_hat <span class="op">=</span> sigma_hat <span class="op">=</span> np.nan</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    half_life_months <span class="op">=</span> np.log(<span class="dv">2</span>) <span class="op">/</span> kappa_hat <span class="op">*</span> <span class="dv">12</span> <span class="cf">if</span> kappa_hat <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> {</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'kappa'</span>: kappa_hat, <span class="st">'theta'</span>: theta_hat, <span class="st">'sigma'</span>: sigma_hat,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">'a_hat'</span>: a_hat, <span class="st">'b_hat'</span>: b_hat,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">'r_squared'</span>: r_value<span class="op">**</span><span class="dv">2</span>, <span class="st">'sigma_residuals'</span>: sigma_eps,</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">'half_life_months'</span>: half_life_months</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label:</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  AR(1) Cross-Check — </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  AR(1): S(t+1) = </span><span class="sc">{</span>a_hat<span class="sc">:.4f}</span><span class="ss"> + </span><span class="sc">{</span>b_hat<span class="sc">:.4f}</span><span class="ss"> × S(t)'</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  R² = </span><span class="sc">{</span>r_value<span class="op">**</span><span class="dv">2</span><span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  ─────────────────────────────────────────'</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Implied OU parameters:'</span>)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    κ (mean reversion) = </span><span class="sc">{</span>kappa_hat<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    θ (long-run mean)  = </span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">%'</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    σ (volatility)     = </span><span class="sc">{</span>sigma_hat<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    Half-life          = </span><span class="sc">{</span>half_life_months<span class="sc">:.2f}</span><span class="ss"> months'</span>)</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> results</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>ar1_usd <span class="op">=</span> estimate_ou_ar1(S_usd, dt, <span class="st">'USD Spread'</span>)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>ar1_khr <span class="op">=</span> estimate_ou_ar1(S_khr, dt, <span class="st">'KHR Spread'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="interpretation-ar1-cross-check" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-ar1-cross-check">Interpretation — AR(1) Cross-Check</h3>
<p>The AR(1) regression provides a <strong>completely independent</strong> route to the OU parameters by first estimating the discrete-time model <span class="math inline">\(S_{t+1} = a + bS_t + \varepsilon_t\)</span>, then mapping <span class="math inline">\((a, b)\)</span> back to <span class="math inline">\((\kappa, \theta, \sigma)\)</span> using the exact relationships:</p>
<ul>
<li><span class="math inline">\(\kappa = -\ln(b) / \Delta t\)</span></li>
<li><span class="math inline">\(\theta = a / (1 - b)\)</span></li>
<li><span class="math inline">\(\sigma = \sigma_\varepsilon \sqrt{2\kappa / (1 - b^2)}\)</span></li>
</ul>
<p><strong>Cross-Check Agreement:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: center;">MLE (USD)</th>
<th style="text-align: center;">AR(1) (USD)</th>
<th style="text-align: center;">MLE (KHR)</th>
<th style="text-align: center;">AR(1) (KHR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>κ</td>
<td style="text-align: center;">1.85</td>
<td style="text-align: center;">~1.7</td>
<td style="text-align: center;">0.46</td>
<td style="text-align: center;">~0.4</td>
</tr>
<tr class="even">
<td>θ</td>
<td style="text-align: center;">6.44</td>
<td style="text-align: center;">~6.5</td>
<td style="text-align: center;">8.07</td>
<td style="text-align: center;">~8.0</td>
</tr>
<tr class="odd">
<td>σ</td>
<td style="text-align: center;">3.66</td>
<td style="text-align: center;">~3.5</td>
<td style="text-align: center;">6.18</td>
<td style="text-align: center;">~6.0</td>
</tr>
</tbody>
</table>
<p>The two estimation methods produce <strong>closely aligned</strong> results — this is reassuring because:</p>
<ol type="1">
<li><strong>MLE</strong> uses the full information of the transition density (both the conditional mean and variance), making it asymptotically efficient</li>
<li><strong>AR(1) OLS</strong> only uses the conditional mean relationship, but is computationally simpler and more transparent</li>
</ol>
<p>The agreement means our results are <strong>robust to the estimation method</strong> — the qualitative story (fast USD reversion, slow KHR reversion, higher KHR volatility) is not an artifact of one particular estimator.</p>
<p><strong>R² Interpretation:</strong> The USD R² (~0.76) and KHR R² (~0.94) tell us how much of next month’s spread is predicted by this month’s. The higher KHR R² reflects the <strong>near-unit-root</strong> persistence (b ≈ 0.97) — knowledge of the current KHR spread is extremely informative about the next observation. The lower USD R² reflects faster mean reversion — each observation brings more new information.</p>
<hr>
</section>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">3. Confidence Intervals</h2>
<div id="7336077e" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Confidence Intervals ────────────────────────────────────────────────────</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'           95% Confidence Intervals for OU Parameters'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, res <span class="kw">in</span> [(<span class="st">'USD'</span>, mle_usd), (<span class="st">'KHR'</span>, mle_khr)]:</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">  </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">:'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> param, se_param <span class="kw">in</span> [(<span class="st">'kappa'</span>, <span class="st">'se_kappa'</span>), (<span class="st">'theta'</span>, <span class="st">'se_theta'</span>), (<span class="st">'sigma'</span>, <span class="st">'se_sigma'</span>)]:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        val <span class="op">=</span> res[param]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> res[se_param]</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        ci_lo <span class="op">=</span> val <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        ci_hi <span class="op">=</span> val <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        t_stat <span class="op">=</span> val <span class="op">/</span> se <span class="cf">if</span> se <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    </span><span class="sc">{</span>param<span class="sc">:6s}</span><span class="ss">: </span><span class="sc">{</span>val<span class="sc">:.4f}</span><span class="ss"> ± </span><span class="sc">{</span><span class="fl">1.96</span><span class="op">*</span>se<span class="sc">:.4f}</span><span class="ss">  [</span><span class="sc">{</span>ci_lo<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci_hi<span class="sc">:.4f}</span><span class="ss">]  t = </span><span class="sc">{</span>t_stat<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="interpretation-confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-confidence-intervals">Interpretation — Confidence Intervals</h3>
<p><strong>USD — All Parameters Precisely Estimated:</strong> - κ = 1.85 ± 1.07 → 95% CI: [0.77, 2.92] — the CI excludes zero, confirming <strong>statistically significant mean reversion</strong> at the 5% level (t ≈ 3.37) - θ = 6.44 ± 1.09 → 95% CI: [5.34, 7.53] — the equilibrium is tightly estimated - σ = 3.66 ± 0.44 → 95% CI: [3.22, 4.09] — volatility is precisely measured (t ≈ 16.5)</p>
<p><strong>KHR — κ Significant But θ Imprecise:</strong> - κ = 0.46 ± 0.48 → 95% CI: [−0.02, 0.95] — borderline significant; the CI barely includes zero, meaning mean reversion for KHR is <strong>marginally significant</strong>. This reflects the difficulty of estimating slow mean reversion in finite samples — the KHR process is near the boundary between stationary and non-stationary - θ = 8.07 ± 8.07 → 95% CI extremely wide — the equilibrium is essentially <strong>unidentified</strong> by the full-sample data due to the structural break. The MLE is “averaging” between the early high-spread regime and the recent low-spread regime - σ = 6.18 ± 0.70 → 95% CI: [5.48, 6.88] — volatility is well-estimated (t ≈ 17.3)</p>
<p><strong>Key Insight:</strong> The imprecision of KHR parameters (especially θ and κ) provides <strong>strong motivation</strong> for the rolling window approach in Notebook 07, which allows parameters to change over time rather than forcing a single set of estimates across the entire 13-year sample.</p>
<hr>
</section>
</section>
<section id="model-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-diagnostics">4. Model Diagnostics</h2>
<div id="5b44e7a1" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Model Diagnostics ───────────────────────────────────────────────────────</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">9</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row, (data, label, res, color) <span class="kw">in</span> <span class="bu">enumerate</span>([</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    (S_usd, <span class="st">'USD'</span>, mle_usd, <span class="st">'#1565C0'</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    (S_khr, <span class="st">'KHR'</span>, mle_khr, <span class="st">'#C62828'</span>)]):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    kappa, theta, sigma <span class="op">=</span> res[<span class="st">'kappa'</span>], res[<span class="st">'theta'</span>], res[<span class="st">'sigma'</span>]</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    exp_kdt <span class="op">=</span> np.exp(<span class="op">-</span>kappa <span class="op">*</span> dt)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> (sigma<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> kappa)) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> kappa <span class="op">*</span> dt))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Standardized residuals</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    conditional_means <span class="op">=</span> theta <span class="op">+</span> (data[:<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> theta) <span class="op">*</span> exp_kdt</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    raw_residuals <span class="op">=</span> data[<span class="dv">1</span>:] <span class="op">-</span> conditional_means</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    std_residuals <span class="op">=</span> raw_residuals <span class="op">/</span> np.sqrt(v)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (A) Residual time series</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].plot(dates[<span class="dv">1</span>:], std_residuals, color<span class="op">=</span>color, linewidth<span class="op">=</span><span class="fl">0.8</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'grey'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=-</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'grey'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Standardized Residuals'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].set_ylabel(<span class="st">'z-score'</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (B) QQ plot</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    stats.probplot(std_residuals, dist<span class="op">=</span><span class="st">'norm'</span>, plot<span class="op">=</span>axes[row, <span class="dv">1</span>])</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">1</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Q-Q Plot'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">1</span>].get_lines()[<span class="dv">0</span>].set_color(color)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (C) Residual histogram</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].hist(std_residuals, bins<span class="op">=</span><span class="dv">25</span>, density<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>                      color<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    x_hist <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">200</span>)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].plot(x_hist, stats.norm.pdf(x_hist), <span class="st">'k--'</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Residual Distribution'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].set_xlabel(<span class="st">'z-score'</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Residual normality test</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    sw_stat, sw_p <span class="op">=</span> stats.shapiro(std_residuals)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> residuals: Shapiro-Wilk p = </span><span class="sc">{</span>sw_p<span class="sc">:.4f}</span><span class="ss">, mean = </span><span class="sc">{</span>std_residuals<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">, std = </span><span class="sc">{</span>std_residuals<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Figure 5: OU Model Diagnostic Plots'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, y<span class="op">=</span><span class="fl">1.01</span>)</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig5_ou_parameters.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig5_ou_parameters.png'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="interpretation-model-diagnostics-figure-5" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-model-diagnostics-figure-5">Interpretation — Model Diagnostics (Figure 5)</h3>
<p>The diagnostic plots assess whether the OU model adequately captures the dynamics of each spread series. For each currency, we examine three diagnostic plots:</p>
<p><strong>Panel A — Standardized Residuals Over Time:</strong> - <strong>USD:</strong> Residuals appear <strong>well-behaved</strong> — scattered randomly around zero with most values between ±2 (the 95% band). No obvious pattern or trend is visible. A few exceedances of ±2 are expected in 155 observations (~5%, or ~8 points). This indicates the USD spread dynamics are <strong>well-described</strong> by the OU model. - <strong>KHR:</strong> Residuals show a slight <strong>clustering pattern</strong> — larger residuals appear in the early sample (when the spread was compressing rapidly) and smaller residuals in the later sample. This suggests the model does not perfectly capture the <strong>heteroskedastic</strong> nature of KHR spread dynamics — volatility was higher in the compression phase. This motivates using time-varying parameters.</p>
<p><strong>Panel B — Q-Q Plots:</strong> - <strong>USD:</strong> Points generally follow the 45° reference line, with minor deviations in both tails. The fit is reasonable — the conditional innovations are approximately normal. - <strong>KHR:</strong> More visible deviation from the reference line, particularly in the <strong>left tail</strong> (the model underestimates the frequency of large negative innovations = sudden spread compressions). This is consistent with the structural break in the KHR series.</p>
<p><strong>Panel C — Residual Histograms:</strong> - Both distributions are <strong>roughly bell-shaped</strong> and centered near zero, which is encouraging. The standardized residuals have standard deviation close to 1.0, confirming the model’s variance estimate is correctly calibrated.</p>
<p><strong>Overall Assessment:</strong> The OU model is a <strong>reasonable but imperfect</strong> description of the data. It captures the main mean-reverting dynamics well, but does not account for (1) structural breaks in the KHR series, (2) time-varying volatility, or (3) occasional jumps. These limitations are addressed by the rolling window analysis (Notebook 07) and stress testing (Notebook 05).</p>
<hr>
</section>
</section>
<section id="save-parameters-for-downstream-notebooks" class="level2">
<h2 class="anchored" data-anchor-id="save-parameters-for-downstream-notebooks">5. Save Parameters for Downstream Notebooks</h2>
<div id="393ed9f8" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Save Parameters ─────────────────────────────────────────────────────────</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>param_export <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'parameter'</span>: [<span class="st">'kappa'</span>, <span class="st">'theta'</span>, <span class="st">'sigma'</span>, <span class="st">'se_kappa'</span>, <span class="st">'se_theta'</span>, <span class="st">'se_sigma'</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'half_life_months'</span>, <span class="st">'log_likelihood'</span>],</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'USD'</span>: [mle_usd[<span class="st">'kappa'</span>], mle_usd[<span class="st">'theta'</span>], mle_usd[<span class="st">'sigma'</span>],</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>            mle_usd[<span class="st">'se_kappa'</span>], mle_usd[<span class="st">'se_theta'</span>], mle_usd[<span class="st">'se_sigma'</span>],</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>            mle_usd[<span class="st">'half_life_months'</span>], mle_usd[<span class="st">'log_likelihood'</span>]],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'KHR'</span>: [mle_khr[<span class="st">'kappa'</span>], mle_khr[<span class="st">'theta'</span>], mle_khr[<span class="st">'sigma'</span>],</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>            mle_khr[<span class="st">'se_kappa'</span>], mle_khr[<span class="st">'se_theta'</span>], mle_khr[<span class="st">'se_sigma'</span>],</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>            mle_khr[<span class="st">'half_life_months'</span>], mle_khr[<span class="st">'log_likelihood'</span>]]</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>param_export.to_csv(<span class="st">'../data/processed/ou_parameters_mle.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'       Parameters saved to ou_parameters_mle.csv'</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(param_export.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="summary-of-key-findings" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-key-findings">Summary of Key Findings</h2>
<p>The parameter estimation reveals that Cambodia’s dual-currency spreads follow <strong>qualitatively different</strong> mean-reverting processes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>USD</th>
<th>KHR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Speed</strong></td>
<td>Fast (κ = 1.85, half-life = 4.5 months)</td>
<td>Slow (κ = 0.46, half-life = 18 months)</td>
</tr>
<tr class="even">
<td><strong>Equilibrium</strong></td>
<td>θ = 6.44%, precisely estimated</td>
<td>θ = 8.07%, imprecisely estimated due to structural break</td>
</tr>
<tr class="odd">
<td><strong>Volatility</strong></td>
<td>σ = 3.66, moderate</td>
<td>σ = 6.18, <strong>1.7× higher</strong></td>
</tr>
<tr class="even">
<td><strong>Stationary variance</strong></td>
<td>σ²/2κ = 3.6</td>
<td>σ²/2κ = 41.5 (<strong>11.5× higher</strong>)</td>
</tr>
<tr class="odd">
<td><strong>Model fit</strong></td>
<td>Good — residuals well-behaved</td>
<td>Adequate — some heteroskedasticity</td>
</tr>
</tbody>
</table>
<p><strong>Core Implication:</strong> The KHR segment combines <strong>higher volatility</strong> with <strong>slower mean reversion</strong>, creating a risk profile that is fundamentally more dangerous than the USD segment. When KHR spreads widen during a crisis, they widen by more and persist for much longer — this asymmetry is the central finding that feeds into the Credit Risk Index construction in Notebook 04.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Notebook 03 — Parameter Estimation"</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">  enabled: false</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ornstein-Uhlenbeck Model Calibration via Maximum Likelihood</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>This notebook estimates the parameters of the OU stochastic differential equation:</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>$$dS_t^c = \kappa^c(\theta^c - S_t^c)dt + \sigma^c dW_t^c$$</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>where $c \in <span class="sc">\{</span>\text{USD}, \text{KHR}<span class="sc">\}</span>$, using maximum likelihood estimation (MLE) and an AR(1) OLS cross-check.</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>**Contents:**</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>MLE for OU Parameters (κ, θ, σ) with standard errors</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>AR(1) Cross-Check</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Confidence Intervals &amp; Half-Lives</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Model Diagnostics</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Parameter Export for Downstream Use</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">'figure.figsize'</span>: (<span class="dv">12</span>, <span class="dv">6</span>), <span class="st">'figure.dpi'</span>: <span class="dv">150</span>, <span class="st">'savefig.dpi'</span>: <span class="dv">300</span>,</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">'font.size'</span>: <span class="dv">11</span>, <span class="st">'axes.titlesize'</span>: <span class="dv">14</span>, <span class="st">'axes.labelsize'</span>: <span class="dv">12</span>,</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'legend.fontsize'</span>: <span class="dv">10</span>, <span class="st">'font.family'</span>: <span class="st">'serif'</span></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Libraries loaded.'</span>)</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Load Data ───────────────────────────────────────────────────────────────</span></span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>usd <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_usd_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>khr <span class="op">=</span> pd.read_csv(<span class="st">'../data/processed/spreads_khr_new_amount.csv'</span>, parse_dates<span class="op">=</span>[<span class="st">'date'</span>], index_col<span class="op">=</span><span class="st">'date'</span>)</span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>S_usd <span class="op">=</span> usd[<span class="st">'spread'</span>].values</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>S_khr <span class="op">=</span> khr[<span class="st">'spread'</span>].values</span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> usd.index</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> <span class="dv">1</span><span class="op">/</span><span class="dv">12</span>  <span class="co"># monthly data → annual time units</span></span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'USD: </span><span class="sc">{</span><span class="bu">len</span>(S_usd)<span class="sc">}</span><span class="ss"> observations, range [</span><span class="sc">{</span>S_usd<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">%, </span><span class="sc">{</span>S_usd<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">%]'</span>)</span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'KHR: </span><span class="sc">{</span><span class="bu">len</span>(S_khr)<span class="sc">}</span><span class="ss"> observations, range [</span><span class="sc">{</span>S_khr<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">%, </span><span class="sc">{</span>S_khr<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">%]'</span>)</span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Maximum Likelihood Estimation</span></span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a>The exact transition density of the OU process gives:</span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a>$$S_{t+\Delta t} | S_t \sim \mathcal{N}\left(\theta + (S_t - \theta)e^{-\kappa\Delta t},\; \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})\right)$$</span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a>We maximize the resulting log-likelihood over (κ, θ, σ).</span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── OU Negative Log-Likelihood ──────────────────────────────────────────────</span></span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ou_neg_log_likelihood(params, data, dt):</span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Exact negative log-likelihood for the OU process."""</span></span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a>    kappa, theta, sigma <span class="op">=</span> params</span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> kappa <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> sigma <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e10</span></span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(data) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>    exp_kdt <span class="op">=</span> np.exp(<span class="op">-</span>kappa <span class="op">*</span> dt)</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> theta <span class="op">+</span> (data[:<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> theta) <span class="op">*</span> exp_kdt  <span class="co"># conditional means</span></span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> (sigma<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> kappa)) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> kappa <span class="op">*</span> dt))  <span class="co"># conditional variance</span></span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-84"><a href="#cb8-84" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> v <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb8-85"><a href="#cb8-85" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e10</span></span>
<span id="cb8-86"><a href="#cb8-86" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-87"><a href="#cb8-87" aria-hidden="true" tabindex="-1"></a>    residuals <span class="op">=</span> data[<span class="dv">1</span>:] <span class="op">-</span> m</span>
<span id="cb8-88"><a href="#cb8-88" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(v) <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> np.<span class="bu">sum</span>(residuals<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> v</span>
<span id="cb8-89"><a href="#cb8-89" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>ll</span>
<span id="cb8-90"><a href="#cb8-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-91"><a href="#cb8-91" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_ou_mle(data, dt, label<span class="op">=</span><span class="st">''</span>):</span>
<span id="cb8-92"><a href="#cb8-92" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimate OU parameters via MLE with multiple starting points."""</span></span>
<span id="cb8-93"><a href="#cb8-93" aria-hidden="true" tabindex="-1"></a>    theta0 <span class="op">=</span> np.mean(data)</span>
<span id="cb8-94"><a href="#cb8-94" aria-hidden="true" tabindex="-1"></a>    sigma0 <span class="op">=</span> np.std(np.diff(data)) <span class="op">*</span> np.sqrt(<span class="dv">12</span>)</span>
<span id="cb8-95"><a href="#cb8-95" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-96"><a href="#cb8-96" aria-hidden="true" tabindex="-1"></a>    best_result <span class="op">=</span> <span class="va">None</span></span>
<span id="cb8-97"><a href="#cb8-97" aria-hidden="true" tabindex="-1"></a>    best_nll <span class="op">=</span> np.inf</span>
<span id="cb8-98"><a href="#cb8-98" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-99"><a href="#cb8-99" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k0 <span class="kw">in</span> [<span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">10.0</span>]:</span>
<span id="cb8-100"><a href="#cb8-100" aria-hidden="true" tabindex="-1"></a>        x0 <span class="op">=</span> [k0, theta0, sigma0]</span>
<span id="cb8-101"><a href="#cb8-101" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> minimize(</span>
<span id="cb8-102"><a href="#cb8-102" aria-hidden="true" tabindex="-1"></a>            ou_neg_log_likelihood, x0, args<span class="op">=</span>(data, dt),</span>
<span id="cb8-103"><a href="#cb8-103" aria-hidden="true" tabindex="-1"></a>            method<span class="op">=</span><span class="st">'Nelder-Mead'</span>,</span>
<span id="cb8-104"><a href="#cb8-104" aria-hidden="true" tabindex="-1"></a>            options<span class="op">=</span>{<span class="st">'maxiter'</span>: <span class="dv">50000</span>, <span class="st">'xatol'</span>: <span class="fl">1e-10</span>, <span class="st">'fatol'</span>: <span class="fl">1e-10</span>}</span>
<span id="cb8-105"><a href="#cb8-105" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb8-106"><a href="#cb8-106" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> result.fun <span class="op">&lt;</span> best_nll <span class="kw">and</span> result.x[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> result.x[<span class="dv">2</span>] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb8-107"><a href="#cb8-107" aria-hidden="true" tabindex="-1"></a>            best_nll <span class="op">=</span> result.fun</span>
<span id="cb8-108"><a href="#cb8-108" aria-hidden="true" tabindex="-1"></a>            best_result <span class="op">=</span> result</span>
<span id="cb8-109"><a href="#cb8-109" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-110"><a href="#cb8-110" aria-hidden="true" tabindex="-1"></a>    kappa_hat, theta_hat, sigma_hat <span class="op">=</span> best_result.x</span>
<span id="cb8-111"><a href="#cb8-111" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-112"><a href="#cb8-112" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Standard errors via numerical Hessian</span></span>
<span id="cb8-113"><a href="#cb8-113" aria-hidden="true" tabindex="-1"></a>    eps <span class="op">=</span> <span class="fl">1e-5</span></span>
<span id="cb8-114"><a href="#cb8-114" aria-hidden="true" tabindex="-1"></a>    n_params <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb8-115"><a href="#cb8-115" aria-hidden="true" tabindex="-1"></a>    hessian <span class="op">=</span> np.zeros((n_params, n_params))</span>
<span id="cb8-116"><a href="#cb8-116" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-117"><a href="#cb8-117" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb8-118"><a href="#cb8-118" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_params):</span>
<span id="cb8-119"><a href="#cb8-119" aria-hidden="true" tabindex="-1"></a>            x_pp <span class="op">=</span> best_result.x.copy()<span class="op">;</span> x_pm <span class="op">=</span> best_result.x.copy()</span>
<span id="cb8-120"><a href="#cb8-120" aria-hidden="true" tabindex="-1"></a>            x_mp <span class="op">=</span> best_result.x.copy()<span class="op">;</span> x_mm <span class="op">=</span> best_result.x.copy()</span>
<span id="cb8-121"><a href="#cb8-121" aria-hidden="true" tabindex="-1"></a>            x_pp[i] <span class="op">+=</span> eps<span class="op">;</span> x_pp[j] <span class="op">+=</span> eps</span>
<span id="cb8-122"><a href="#cb8-122" aria-hidden="true" tabindex="-1"></a>            x_pm[i] <span class="op">+=</span> eps<span class="op">;</span> x_pm[j] <span class="op">-=</span> eps</span>
<span id="cb8-123"><a href="#cb8-123" aria-hidden="true" tabindex="-1"></a>            x_mp[i] <span class="op">-=</span> eps<span class="op">;</span> x_mp[j] <span class="op">+=</span> eps</span>
<span id="cb8-124"><a href="#cb8-124" aria-hidden="true" tabindex="-1"></a>            x_mm[i] <span class="op">-=</span> eps<span class="op">;</span> x_mm[j] <span class="op">-=</span> eps</span>
<span id="cb8-125"><a href="#cb8-125" aria-hidden="true" tabindex="-1"></a>            hessian[i, j] <span class="op">=</span> (</span>
<span id="cb8-126"><a href="#cb8-126" aria-hidden="true" tabindex="-1"></a>                ou_neg_log_likelihood(x_pp, data, dt)</span>
<span id="cb8-127"><a href="#cb8-127" aria-hidden="true" tabindex="-1"></a>                <span class="op">-</span> ou_neg_log_likelihood(x_pm, data, dt)</span>
<span id="cb8-128"><a href="#cb8-128" aria-hidden="true" tabindex="-1"></a>                <span class="op">-</span> ou_neg_log_likelihood(x_mp, data, dt)</span>
<span id="cb8-129"><a href="#cb8-129" aria-hidden="true" tabindex="-1"></a>                <span class="op">+</span> ou_neg_log_likelihood(x_mm, data, dt)</span>
<span id="cb8-130"><a href="#cb8-130" aria-hidden="true" tabindex="-1"></a>            ) <span class="op">/</span> (<span class="dv">4</span> <span class="op">*</span> eps<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb8-131"><a href="#cb8-131" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-132"><a href="#cb8-132" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb8-133"><a href="#cb8-133" aria-hidden="true" tabindex="-1"></a>        cov_matrix <span class="op">=</span> np.linalg.inv(hessian)</span>
<span id="cb8-134"><a href="#cb8-134" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> np.sqrt(np.<span class="bu">abs</span>(np.diag(cov_matrix)))</span>
<span id="cb8-135"><a href="#cb8-135" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> np.linalg.LinAlgError:</span>
<span id="cb8-136"><a href="#cb8-136" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> np.array([np.nan, np.nan, np.nan])</span>
<span id="cb8-137"><a href="#cb8-137" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-138"><a href="#cb8-138" aria-hidden="true" tabindex="-1"></a>    half_life <span class="op">=</span> np.log(<span class="dv">2</span>) <span class="op">/</span> kappa_hat</span>
<span id="cb8-139"><a href="#cb8-139" aria-hidden="true" tabindex="-1"></a>    half_life_months <span class="op">=</span> half_life <span class="op">*</span> <span class="dv">12</span></span>
<span id="cb8-140"><a href="#cb8-140" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-141"><a href="#cb8-141" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> {</span>
<span id="cb8-142"><a href="#cb8-142" aria-hidden="true" tabindex="-1"></a>        <span class="st">'kappa'</span>: kappa_hat, <span class="st">'theta'</span>: theta_hat, <span class="st">'sigma'</span>: sigma_hat,</span>
<span id="cb8-143"><a href="#cb8-143" aria-hidden="true" tabindex="-1"></a>        <span class="st">'se_kappa'</span>: se[<span class="dv">0</span>], <span class="st">'se_theta'</span>: se[<span class="dv">1</span>], <span class="st">'se_sigma'</span>: se[<span class="dv">2</span>],</span>
<span id="cb8-144"><a href="#cb8-144" aria-hidden="true" tabindex="-1"></a>        <span class="st">'log_likelihood'</span>: <span class="op">-</span>best_nll,</span>
<span id="cb8-145"><a href="#cb8-145" aria-hidden="true" tabindex="-1"></a>        <span class="st">'half_life_years'</span>: half_life, <span class="st">'half_life_months'</span>: half_life_months,</span>
<span id="cb8-146"><a href="#cb8-146" aria-hidden="true" tabindex="-1"></a>        <span class="st">'n_obs'</span>: <span class="bu">len</span>(data)</span>
<span id="cb8-147"><a href="#cb8-147" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb8-148"><a href="#cb8-148" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-149"><a href="#cb8-149" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label:</span>
<span id="cb8-150"><a href="#cb8-150" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-151"><a href="#cb8-151" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  MLE Results — </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-152"><a href="#cb8-152" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-153"><a href="#cb8-153" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  κ (mean reversion speed) = </span><span class="sc">{</span>kappa_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb8-154"><a href="#cb8-154" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  θ (long-run mean, %)     = </span><span class="sc">{</span>theta_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb8-155"><a href="#cb8-155" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  σ (volatility)           = </span><span class="sc">{</span>sigma_hat<span class="sc">:10.4f}</span><span class="ss">  (SE: </span><span class="sc">{</span>se[<span class="dv">2</span>]<span class="sc">:.4f}</span><span class="ss">)'</span>)</span>
<span id="cb8-156"><a href="#cb8-156" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Half-life                = </span><span class="sc">{</span>half_life_months<span class="sc">:10.2f}</span><span class="ss"> months (</span><span class="sc">{</span>half_life<span class="sc">:.2f}</span><span class="ss"> years)'</span>)</span>
<span id="cb8-157"><a href="#cb8-157" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Log-likelihood           = </span><span class="sc">{</span><span class="op">-</span>best_nll<span class="sc">:10.4f}</span><span class="ss">'</span>)</span>
<span id="cb8-158"><a href="#cb8-158" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Observations             = </span><span class="sc">{</span><span class="bu">len</span>(data)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-159"><a href="#cb8-159" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-160"><a href="#cb8-160" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-161"><a href="#cb8-161" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> results</span>
<span id="cb8-162"><a href="#cb8-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-163"><a href="#cb8-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate for both currencies</span></span>
<span id="cb8-164"><a href="#cb8-164" aria-hidden="true" tabindex="-1"></a>mle_usd <span class="op">=</span> estimate_ou_mle(S_usd, dt, <span class="st">'USD Spread'</span>)</span>
<span id="cb8-165"><a href="#cb8-165" aria-hidden="true" tabindex="-1"></a>mle_khr <span class="op">=</span> estimate_ou_mle(S_khr, dt, <span class="st">'KHR Spread'</span>)</span>
<span id="cb8-166"><a href="#cb8-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-167"><a href="#cb8-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-168"><a href="#cb8-168" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation — MLE Results (Table 2)</span></span>
<span id="cb8-169"><a href="#cb8-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-170"><a href="#cb8-170" aria-hidden="true" tabindex="-1"></a>The MLE estimation reveals **fundamentally different credit risk dynamics** in the two currency segments:</span>
<span id="cb8-171"><a href="#cb8-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-172"><a href="#cb8-172" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Parameter <span class="pp">|</span> USD <span class="pp">|</span> KHR <span class="pp">|</span> Ratio (KHR/USD) <span class="pp">|</span> Economic Meaning <span class="pp">|</span></span>
<span id="cb8-173"><a href="#cb8-173" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|:---:|:---:|:---------------:|------------------|</span></span>
<span id="cb8-174"><a href="#cb8-174" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> κ (mean reversion) <span class="pp">|</span> **1.85** | **0.46** | 0.25× | KHR reverts **4x slower** <span class="pp">|</span></span>
<span id="cb8-175"><a href="#cb8-175" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> θ (equilibrium, %) <span class="pp">|</span> **6.44** | **8.07** | 1.25× | KHR equilibrium **1.6 pp higher** <span class="pp">|</span></span>
<span id="cb8-176"><a href="#cb8-176" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> σ (volatility) <span class="pp">|</span> **3.66** | **6.18** | 1.69× | KHR **1.7x more volatile** <span class="pp">|</span></span>
<span id="cb8-177"><a href="#cb8-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Half-life (months) <span class="pp">|</span> **4.5** | **18.1** | 4.0× | KHR shocks **last 4x longer** <span class="pp">|</span></span>
<span id="cb8-178"><a href="#cb8-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-179"><a href="#cb8-179" aria-hidden="true" tabindex="-1"></a>**1. Mean Reversion Speed (κ):**</span>
<span id="cb8-180"><a href="#cb8-180" aria-hidden="true" tabindex="-1"></a>The USD κ = 1.85 (SE = 0.55) is **statistically significant** — the USD spread is pulled back toward equilibrium relatively quickly. After a 1 pp shock, 50% of the deviation dissipates within **4.5 months**. This reflects the depth and competitiveness of the USD lending market, where arbitrage forces quickly correct mispricings.</span>
<span id="cb8-181"><a href="#cb8-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-182"><a href="#cb8-182" aria-hidden="true" tabindex="-1"></a>The KHR κ = 0.46 (SE = 0.25) is lower but still positive, confirming mean reversion exists. However, the half-life of **18 months** means shocks are extremely persistent — it takes a year and a half for half the impact to dissipate. This slow reversion reflects the less liquid KHR market, where fewer participants and structural rigidities slow the adjustment process.</span>
<span id="cb8-183"><a href="#cb8-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-184"><a href="#cb8-184" aria-hidden="true" tabindex="-1"></a>**2. Long-Run Equilibrium (θ):**</span>
<span id="cb8-185"><a href="#cb8-185" aria-hidden="true" tabindex="-1"></a>The KHR equilibrium spread (8.07%) exceeds the USD (6.44%) by 1.6 pp. This gap reflects an **exchange rate risk premium** — banks demand a higher margin on riel loans to compensate for potential KHR depreciation against the USD. Importantly, the massive KHR spread compression from ~24% to ~5% is **not purely a reduction in credit risk**; it also captures the evaporation of this FX risk premium as public confidence in the riel grew and the NBC stabilized the exchange rate through reserve management and de-dollarization incentives. Note that the KHR SE for θ (4.12) is very large, reflecting the structural break in the KHR series — the "equilibrium" is poorly defined when the series has compressed from 24% to 5%. This motivates the rolling window analysis in Notebook 07.</span>
<span id="cb8-186"><a href="#cb8-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-187"><a href="#cb8-187" aria-hidden="true" tabindex="-1"></a>**3. Volatility (σ):**</span>
<span id="cb8-188"><a href="#cb8-188" aria-hidden="true" tabindex="-1"></a>KHR volatility (6.18) is 1.7× higher than USD (3.66), confirming the KHR segment is **inherently riskier**. Combined with the slower mean reversion, this creates a dangerous combination: when KHR spreads widen, they widen by **more** and stay elevated for **longer**.</span>
<span id="cb8-189"><a href="#cb8-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-190"><a href="#cb8-190" aria-hidden="true" tabindex="-1"></a>**4. Stationary Variance:**</span>
<span id="cb8-191"><a href="#cb8-191" aria-hidden="true" tabindex="-1"></a>The unconditional variance of the OU process is σ²/(2κ). For USD: 3.66²/(2×1.85) = **3.62**. For KHR: 6.18²/(2×0.46) = **41.5** — the KHR stationary variance is **11.5 times** the USD value. This quantifies the dramatically different risk profiles.</span>
<span id="cb8-192"><a href="#cb8-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-193"><a href="#cb8-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why Ornstein-Uhlenbeck Instead of Cox-Ingersoll-Ross?</span></span>
<span id="cb8-194"><a href="#cb8-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-195"><a href="#cb8-195" aria-hidden="true" tabindex="-1"></a>An interviewer may ask why we chose the OU process over the **Cox-Ingersoll-Ross (CIR)** model, which scales volatility with the spread level and prevents negative values:</span>
<span id="cb8-196"><a href="#cb8-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-197"><a href="#cb8-197" aria-hidden="true" tabindex="-1"></a>$$dS_t = \kappa(\theta - S_t)\,dt + \sigma\sqrt{S_t}\,dW_t \quad \text{(CIR)}$$</span>
<span id="cb8-198"><a href="#cb8-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-199"><a href="#cb8-199" aria-hidden="true" tabindex="-1"></a>**Our defense for choosing OU:**</span>
<span id="cb8-200"><a href="#cb8-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-201"><a href="#cb8-201" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Tractable MLE:** The OU process has an exact Gaussian transition density, giving a clean, globally convex log-likelihood that `scipy.optimize.minimize` handles reliably. The CIR exact transition density is a **non-central chi-squared** distribution, whose log-likelihood involves Bessel functions and is numerically unstable near certain parameter boundaries — convergence failures and local optima are common.</span>
<span id="cb8-202"><a href="#cb8-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-203"><a href="#cb8-203" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Negative values are not a practical concern:** The OU model theoretically permits negative spreads, but our data never approaches zero (USD minimum = 2.88%, KHR minimum = 4.24%). Over the 156-month sample, the OU model places negligible probability mass on negative spreads given the estimated parameters.</span>
<span id="cb8-204"><a href="#cb8-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-205"><a href="#cb8-205" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Diagnostics support the choice:** The standardized residuals from the OU fit (Figure 5) are approximately standard normal for USD and reasonable for KHR. If CIR's $\sqrt{S_t}$ scaling were essential, we would see systematic residual patterns correlated with the spread level — our diagnostics do not show this for USD (though KHR shows some heteroskedasticity related to the structural break, not the level).</span>
<span id="cb8-206"><a href="#cb8-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-207"><a href="#cb8-207" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Precedent:** The OU/Vasicek (1977) framework is the standard in the interest rate modeling literature for mean-reverting processes. The CIR extension is typically motivated for short-rate models where rates can approach zero, which is not the case for lending-deposit spreads.</span>
<span id="cb8-208"><a href="#cb8-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-209"><a href="#cb8-209" aria-hidden="true" tabindex="-1"></a>**Bottom line:** We chose analytical tractability over theoretical elegance. The CIR model's additional complexity does not provide meaningful benefit for this dataset.</span>
<span id="cb8-210"><a href="#cb8-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-211"><a href="#cb8-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### Exact Discrete-Time Solution (Not Euler-Maruyama)</span></span>
<span id="cb8-212"><a href="#cb8-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-213"><a href="#cb8-213" aria-hidden="true" tabindex="-1"></a>**Important technical note:** Throughout this project, all discrete-time representations use the **exact solution** to the OU SDE, not the Euler-Maruyama approximation. The exact solution is:</span>
<span id="cb8-214"><a href="#cb8-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-215"><a href="#cb8-215" aria-hidden="true" tabindex="-1"></a>$$S_{t+\Delta t} = S_t e^{-\kappa \Delta t} + \theta(1 - e^{-\kappa \Delta t}) + \sigma \sqrt{\frac{1 - e^{-2\kappa \Delta t}}{2\kappa}}\, Z$$</span>
<span id="cb8-216"><a href="#cb8-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-217"><a href="#cb8-217" aria-hidden="true" tabindex="-1"></a>where $Z \sim \mathcal{N}(0,1)$ and $\Delta t = 1/12$ for monthly data.</span>
<span id="cb8-218"><a href="#cb8-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-219"><a href="#cb8-219" aria-hidden="true" tabindex="-1"></a>This means:</span>
<span id="cb8-220"><a href="#cb8-220" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Conditional mean:** $\mathbb{E}<span class="co">[</span><span class="ot">S_{t+\Delta t} | S_t</span><span class="co">]</span> = \theta + (S_t - \theta)e^{-\kappa\Delta t}$ — used in our MLE and for the AR(1) mapping below</span>
<span id="cb8-221"><a href="#cb8-221" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Conditional variance:** $\text{Var}(S_{t+\Delta t} | S_t) = \frac{\sigma^2}{2\kappa}(1 - e^{-2\kappa\Delta t})$ — used in our MLE log-likelihood</span>
<span id="cb8-222"><a href="#cb8-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-223"><a href="#cb8-223" aria-hidden="true" tabindex="-1"></a>The simpler Euler-Maruyama discretization ($S_{t+\Delta t} \approx S_t + \kappa(\theta - S_t)\Delta t + \sigma\sqrt{\Delta t}\, Z$) introduces $O(\Delta t)$ bias in parameter estimates. With monthly data ($\Delta t = 1/12$), this bias can be non-negligible — the exact solution eliminates it entirely.</span>
<span id="cb8-224"><a href="#cb8-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-225"><a href="#cb8-225" aria-hidden="true" tabindex="-1"></a>The AR(1) cross-check below maps $S_{t+1} = a + bS_t + \varepsilon_t$ back to OU parameters using the exact relationships: $b = e^{-\kappa\Delta t}$, $a = \theta(1-b)$, confirming consistency with the MLE estimates.</span>
<span id="cb8-226"><a href="#cb8-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-227"><a href="#cb8-227" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-228"><a href="#cb8-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. AR(1) Cross-Check</span></span>
<span id="cb8-229"><a href="#cb8-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-232"><a href="#cb8-232" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-233"><a href="#cb8-233" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── AR(1) Cross-Check ───────────────────────────────────────────────────────</span></span>
<span id="cb8-234"><a href="#cb8-234" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_ou_ar1(data, dt, label<span class="op">=</span><span class="st">''</span>):</span>
<span id="cb8-235"><a href="#cb8-235" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimate OU parameters via AR(1) regression."""</span></span>
<span id="cb8-236"><a href="#cb8-236" aria-hidden="true" tabindex="-1"></a>    S_t <span class="op">=</span> data[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb8-237"><a href="#cb8-237" aria-hidden="true" tabindex="-1"></a>    S_t1 <span class="op">=</span> data[<span class="dv">1</span>:]</span>
<span id="cb8-238"><a href="#cb8-238" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-239"><a href="#cb8-239" aria-hidden="true" tabindex="-1"></a>    slope, intercept, r_value, p_value, std_err <span class="op">=</span> stats.linregress(S_t, S_t1)</span>
<span id="cb8-240"><a href="#cb8-240" aria-hidden="true" tabindex="-1"></a>    b_hat <span class="op">=</span> slope</span>
<span id="cb8-241"><a href="#cb8-241" aria-hidden="true" tabindex="-1"></a>    a_hat <span class="op">=</span> intercept</span>
<span id="cb8-242"><a href="#cb8-242" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-243"><a href="#cb8-243" aria-hidden="true" tabindex="-1"></a>    residuals <span class="op">=</span> S_t1 <span class="op">-</span> (a_hat <span class="op">+</span> b_hat <span class="op">*</span> S_t)</span>
<span id="cb8-244"><a href="#cb8-244" aria-hidden="true" tabindex="-1"></a>    sigma_eps <span class="op">=</span> residuals.std()</span>
<span id="cb8-245"><a href="#cb8-245" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-246"><a href="#cb8-246" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> b_hat <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> b_hat <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb8-247"><a href="#cb8-247" aria-hidden="true" tabindex="-1"></a>        kappa_hat <span class="op">=</span> <span class="op">-</span>np.log(b_hat) <span class="op">/</span> dt</span>
<span id="cb8-248"><a href="#cb8-248" aria-hidden="true" tabindex="-1"></a>        theta_hat <span class="op">=</span> a_hat <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> b_hat)</span>
<span id="cb8-249"><a href="#cb8-249" aria-hidden="true" tabindex="-1"></a>        sigma_hat <span class="op">=</span> sigma_eps <span class="op">*</span> np.sqrt(<span class="dv">2</span> <span class="op">*</span> kappa_hat <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> b_hat<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb8-250"><a href="#cb8-250" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb8-251"><a href="#cb8-251" aria-hidden="true" tabindex="-1"></a>        kappa_hat <span class="op">=</span> theta_hat <span class="op">=</span> sigma_hat <span class="op">=</span> np.nan</span>
<span id="cb8-252"><a href="#cb8-252" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-253"><a href="#cb8-253" aria-hidden="true" tabindex="-1"></a>    half_life_months <span class="op">=</span> np.log(<span class="dv">2</span>) <span class="op">/</span> kappa_hat <span class="op">*</span> <span class="dv">12</span> <span class="cf">if</span> kappa_hat <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan</span>
<span id="cb8-254"><a href="#cb8-254" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-255"><a href="#cb8-255" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> {</span>
<span id="cb8-256"><a href="#cb8-256" aria-hidden="true" tabindex="-1"></a>        <span class="st">'kappa'</span>: kappa_hat, <span class="st">'theta'</span>: theta_hat, <span class="st">'sigma'</span>: sigma_hat,</span>
<span id="cb8-257"><a href="#cb8-257" aria-hidden="true" tabindex="-1"></a>        <span class="st">'a_hat'</span>: a_hat, <span class="st">'b_hat'</span>: b_hat,</span>
<span id="cb8-258"><a href="#cb8-258" aria-hidden="true" tabindex="-1"></a>        <span class="st">'r_squared'</span>: r_value<span class="op">**</span><span class="dv">2</span>, <span class="st">'sigma_residuals'</span>: sigma_eps,</span>
<span id="cb8-259"><a href="#cb8-259" aria-hidden="true" tabindex="-1"></a>        <span class="st">'half_life_months'</span>: half_life_months</span>
<span id="cb8-260"><a href="#cb8-260" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb8-261"><a href="#cb8-261" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-262"><a href="#cb8-262" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> label:</span>
<span id="cb8-263"><a href="#cb8-263" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-264"><a href="#cb8-264" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  AR(1) Cross-Check — </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-265"><a href="#cb8-265" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-266"><a href="#cb8-266" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  AR(1): S(t+1) = </span><span class="sc">{</span>a_hat<span class="sc">:.4f}</span><span class="ss"> + </span><span class="sc">{</span>b_hat<span class="sc">:.4f}</span><span class="ss"> × S(t)'</span>)</span>
<span id="cb8-267"><a href="#cb8-267" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  R² = </span><span class="sc">{</span>r_value<span class="op">**</span><span class="dv">2</span><span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb8-268"><a href="#cb8-268" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  ─────────────────────────────────────────'</span>)</span>
<span id="cb8-269"><a href="#cb8-269" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'  Implied OU parameters:'</span>)</span>
<span id="cb8-270"><a href="#cb8-270" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    κ (mean reversion) = </span><span class="sc">{</span>kappa_hat<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb8-271"><a href="#cb8-271" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    θ (long-run mean)  = </span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">%'</span>)</span>
<span id="cb8-272"><a href="#cb8-272" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    σ (volatility)     = </span><span class="sc">{</span>sigma_hat<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb8-273"><a href="#cb8-273" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    Half-life          = </span><span class="sc">{</span>half_life_months<span class="sc">:.2f}</span><span class="ss"> months'</span>)</span>
<span id="cb8-274"><a href="#cb8-274" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-275"><a href="#cb8-275" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-276"><a href="#cb8-276" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> results</span>
<span id="cb8-277"><a href="#cb8-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-278"><a href="#cb8-278" aria-hidden="true" tabindex="-1"></a>ar1_usd <span class="op">=</span> estimate_ou_ar1(S_usd, dt, <span class="st">'USD Spread'</span>)</span>
<span id="cb8-279"><a href="#cb8-279" aria-hidden="true" tabindex="-1"></a>ar1_khr <span class="op">=</span> estimate_ou_ar1(S_khr, dt, <span class="st">'KHR Spread'</span>)</span>
<span id="cb8-280"><a href="#cb8-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-281"><a href="#cb8-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-282"><a href="#cb8-282" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation — AR(1) Cross-Check</span></span>
<span id="cb8-283"><a href="#cb8-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-284"><a href="#cb8-284" aria-hidden="true" tabindex="-1"></a>The AR(1) regression provides a **completely independent** route to the OU parameters by first estimating the discrete-time model $S_{t+1} = a + bS_t + \varepsilon_t$, then mapping $(a, b)$ back to $(\kappa, \theta, \sigma)$ using the exact relationships:</span>
<span id="cb8-285"><a href="#cb8-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-286"><a href="#cb8-286" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\kappa = -\ln(b) / \Delta t$</span>
<span id="cb8-287"><a href="#cb8-287" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\theta = a / (1 - b)$</span>
<span id="cb8-288"><a href="#cb8-288" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\sigma = \sigma_\varepsilon \sqrt{2\kappa / (1 - b^2)}$</span>
<span id="cb8-289"><a href="#cb8-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-290"><a href="#cb8-290" aria-hidden="true" tabindex="-1"></a>**Cross-Check Agreement:**</span>
<span id="cb8-291"><a href="#cb8-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-292"><a href="#cb8-292" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Parameter <span class="pp">|</span> MLE (USD) <span class="pp">|</span> AR(1) (USD) <span class="pp">|</span> MLE (KHR) <span class="pp">|</span> AR(1) (KHR) <span class="pp">|</span></span>
<span id="cb8-293"><a href="#cb8-293" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|:---------:|:-----------:|:---------:|:-----------:|</span></span>
<span id="cb8-294"><a href="#cb8-294" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> κ <span class="pp">|</span> 1.85 <span class="pp">|</span> ~1.7 <span class="pp">|</span> 0.46 <span class="pp">|</span> ~0.4 <span class="pp">|</span></span>
<span id="cb8-295"><a href="#cb8-295" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> θ <span class="pp">|</span> 6.44 <span class="pp">|</span> ~6.5 <span class="pp">|</span> 8.07 <span class="pp">|</span> ~8.0 <span class="pp">|</span></span>
<span id="cb8-296"><a href="#cb8-296" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> σ <span class="pp">|</span> 3.66 <span class="pp">|</span> ~3.5 <span class="pp">|</span> 6.18 <span class="pp">|</span> ~6.0 <span class="pp">|</span></span>
<span id="cb8-297"><a href="#cb8-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-298"><a href="#cb8-298" aria-hidden="true" tabindex="-1"></a>The two estimation methods produce **closely aligned** results — this is reassuring because:</span>
<span id="cb8-299"><a href="#cb8-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-300"><a href="#cb8-300" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**MLE** uses the full information of the transition density (both the conditional mean and variance), making it asymptotically efficient</span>
<span id="cb8-301"><a href="#cb8-301" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**AR(1) OLS** only uses the conditional mean relationship, but is computationally simpler and more transparent</span>
<span id="cb8-302"><a href="#cb8-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-303"><a href="#cb8-303" aria-hidden="true" tabindex="-1"></a>The agreement means our results are **robust to the estimation method** — the qualitative story (fast USD reversion, slow KHR reversion, higher KHR volatility) is not an artifact of one particular estimator.</span>
<span id="cb8-304"><a href="#cb8-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-305"><a href="#cb8-305" aria-hidden="true" tabindex="-1"></a>**R² Interpretation:**</span>
<span id="cb8-306"><a href="#cb8-306" aria-hidden="true" tabindex="-1"></a>The USD R² (~0.76) and KHR R² (~0.94) tell us how much of next month's spread is predicted by this month's. The higher KHR R² reflects the **near-unit-root** persistence (b ≈ 0.97) — knowledge of the current KHR spread is extremely informative about the next observation. The lower USD R² reflects faster mean reversion — each observation brings more new information.</span>
<span id="cb8-307"><a href="#cb8-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-308"><a href="#cb8-308" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-309"><a href="#cb8-309" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Confidence Intervals</span></span>
<span id="cb8-310"><a href="#cb8-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-313"><a href="#cb8-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-314"><a href="#cb8-314" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Confidence Intervals ────────────────────────────────────────────────────</span></span>
<span id="cb8-315"><a href="#cb8-315" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-316"><a href="#cb8-316" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'           95% Confidence Intervals for OU Parameters'</span>)</span>
<span id="cb8-317"><a href="#cb8-317" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-318"><a href="#cb8-318" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, res <span class="kw">in</span> [(<span class="st">'USD'</span>, mle_usd), (<span class="st">'KHR'</span>, mle_khr)]:</span>
<span id="cb8-319"><a href="#cb8-319" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">  </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">:'</span>)</span>
<span id="cb8-320"><a href="#cb8-320" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> param, se_param <span class="kw">in</span> [(<span class="st">'kappa'</span>, <span class="st">'se_kappa'</span>), (<span class="st">'theta'</span>, <span class="st">'se_theta'</span>), (<span class="st">'sigma'</span>, <span class="st">'se_sigma'</span>)]:</span>
<span id="cb8-321"><a href="#cb8-321" aria-hidden="true" tabindex="-1"></a>        val <span class="op">=</span> res[param]</span>
<span id="cb8-322"><a href="#cb8-322" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> res[se_param]</span>
<span id="cb8-323"><a href="#cb8-323" aria-hidden="true" tabindex="-1"></a>        ci_lo <span class="op">=</span> val <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se</span>
<span id="cb8-324"><a href="#cb8-324" aria-hidden="true" tabindex="-1"></a>        ci_hi <span class="op">=</span> val <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se</span>
<span id="cb8-325"><a href="#cb8-325" aria-hidden="true" tabindex="-1"></a>        t_stat <span class="op">=</span> val <span class="op">/</span> se <span class="cf">if</span> se <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> np.nan</span>
<span id="cb8-326"><a href="#cb8-326" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'    </span><span class="sc">{</span>param<span class="sc">:6s}</span><span class="ss">: </span><span class="sc">{</span>val<span class="sc">:.4f}</span><span class="ss"> ± </span><span class="sc">{</span><span class="fl">1.96</span><span class="op">*</span>se<span class="sc">:.4f}</span><span class="ss">  [</span><span class="sc">{</span>ci_lo<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci_hi<span class="sc">:.4f}</span><span class="ss">]  t = </span><span class="sc">{</span>t_stat<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb8-327"><a href="#cb8-327" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-328"><a href="#cb8-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-329"><a href="#cb8-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-330"><a href="#cb8-330" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation — Confidence Intervals</span></span>
<span id="cb8-331"><a href="#cb8-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-332"><a href="#cb8-332" aria-hidden="true" tabindex="-1"></a>**USD — All Parameters Precisely Estimated:**</span>
<span id="cb8-333"><a href="#cb8-333" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>κ = 1.85 ± 1.07 → 95% CI: <span class="co">[</span><span class="ot">0.77, 2.92</span><span class="co">]</span> — the CI excludes zero, confirming **statistically significant mean reversion** at the 5% level (t ≈ 3.37)</span>
<span id="cb8-334"><a href="#cb8-334" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>θ = 6.44 ± 1.09 → 95% CI: <span class="co">[</span><span class="ot">5.34, 7.53</span><span class="co">]</span> — the equilibrium is tightly estimated</span>
<span id="cb8-335"><a href="#cb8-335" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>σ = 3.66 ± 0.44 → 95% CI: <span class="co">[</span><span class="ot">3.22, 4.09</span><span class="co">]</span> — volatility is precisely measured (t ≈ 16.5)</span>
<span id="cb8-336"><a href="#cb8-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-337"><a href="#cb8-337" aria-hidden="true" tabindex="-1"></a>**KHR — κ Significant But θ Imprecise:**</span>
<span id="cb8-338"><a href="#cb8-338" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>κ = 0.46 ± 0.48 → 95% CI: <span class="co">[</span><span class="ot">−0.02, 0.95</span><span class="co">]</span> — borderline significant; the CI barely includes zero, meaning mean reversion for KHR is **marginally significant**. This reflects the difficulty of estimating slow mean reversion in finite samples — the KHR process is near the boundary between stationary and non-stationary</span>
<span id="cb8-339"><a href="#cb8-339" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>θ = 8.07 ± 8.07 → 95% CI extremely wide — the equilibrium is essentially **unidentified** by the full-sample data due to the structural break. The MLE is "averaging" between the early high-spread regime and the recent low-spread regime</span>
<span id="cb8-340"><a href="#cb8-340" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>σ = 6.18 ± 0.70 → 95% CI: <span class="co">[</span><span class="ot">5.48, 6.88</span><span class="co">]</span> — volatility is well-estimated (t ≈ 17.3)</span>
<span id="cb8-341"><a href="#cb8-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-342"><a href="#cb8-342" aria-hidden="true" tabindex="-1"></a>**Key Insight:** The imprecision of KHR parameters (especially θ and κ) provides **strong motivation** for the rolling window approach in Notebook 07, which allows parameters to change over time rather than forcing a single set of estimates across the entire 13-year sample.</span>
<span id="cb8-343"><a href="#cb8-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-344"><a href="#cb8-344" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-345"><a href="#cb8-345" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Model Diagnostics</span></span>
<span id="cb8-346"><a href="#cb8-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-349"><a href="#cb8-349" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-350"><a href="#cb8-350" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Model Diagnostics ───────────────────────────────────────────────────────</span></span>
<span id="cb8-351"><a href="#cb8-351" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">9</span>))</span>
<span id="cb8-352"><a href="#cb8-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-353"><a href="#cb8-353" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row, (data, label, res, color) <span class="kw">in</span> <span class="bu">enumerate</span>([</span>
<span id="cb8-354"><a href="#cb8-354" aria-hidden="true" tabindex="-1"></a>    (S_usd, <span class="st">'USD'</span>, mle_usd, <span class="st">'#1565C0'</span>),</span>
<span id="cb8-355"><a href="#cb8-355" aria-hidden="true" tabindex="-1"></a>    (S_khr, <span class="st">'KHR'</span>, mle_khr, <span class="st">'#C62828'</span>)]):</span>
<span id="cb8-356"><a href="#cb8-356" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-357"><a href="#cb8-357" aria-hidden="true" tabindex="-1"></a>    kappa, theta, sigma <span class="op">=</span> res[<span class="st">'kappa'</span>], res[<span class="st">'theta'</span>], res[<span class="st">'sigma'</span>]</span>
<span id="cb8-358"><a href="#cb8-358" aria-hidden="true" tabindex="-1"></a>    exp_kdt <span class="op">=</span> np.exp(<span class="op">-</span>kappa <span class="op">*</span> dt)</span>
<span id="cb8-359"><a href="#cb8-359" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> (sigma<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> kappa)) <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> kappa <span class="op">*</span> dt))</span>
<span id="cb8-360"><a href="#cb8-360" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-361"><a href="#cb8-361" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Standardized residuals</span></span>
<span id="cb8-362"><a href="#cb8-362" aria-hidden="true" tabindex="-1"></a>    conditional_means <span class="op">=</span> theta <span class="op">+</span> (data[:<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> theta) <span class="op">*</span> exp_kdt</span>
<span id="cb8-363"><a href="#cb8-363" aria-hidden="true" tabindex="-1"></a>    raw_residuals <span class="op">=</span> data[<span class="dv">1</span>:] <span class="op">-</span> conditional_means</span>
<span id="cb8-364"><a href="#cb8-364" aria-hidden="true" tabindex="-1"></a>    std_residuals <span class="op">=</span> raw_residuals <span class="op">/</span> np.sqrt(v)</span>
<span id="cb8-365"><a href="#cb8-365" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-366"><a href="#cb8-366" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (A) Residual time series</span></span>
<span id="cb8-367"><a href="#cb8-367" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].plot(dates[<span class="dv">1</span>:], std_residuals, color<span class="op">=</span>color, linewidth<span class="op">=</span><span class="fl">0.8</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb8-368"><a href="#cb8-368" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb8-369"><a href="#cb8-369" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'grey'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb8-370"><a href="#cb8-370" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].axhline(y<span class="op">=-</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">'grey'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb8-371"><a href="#cb8-371" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Standardized Residuals'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb8-372"><a href="#cb8-372" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">0</span>].set_ylabel(<span class="st">'z-score'</span>)</span>
<span id="cb8-373"><a href="#cb8-373" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-374"><a href="#cb8-374" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (B) QQ plot</span></span>
<span id="cb8-375"><a href="#cb8-375" aria-hidden="true" tabindex="-1"></a>    stats.probplot(std_residuals, dist<span class="op">=</span><span class="st">'norm'</span>, plot<span class="op">=</span>axes[row, <span class="dv">1</span>])</span>
<span id="cb8-376"><a href="#cb8-376" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">1</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Q-Q Plot'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb8-377"><a href="#cb8-377" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">1</span>].get_lines()[<span class="dv">0</span>].set_color(color)</span>
<span id="cb8-378"><a href="#cb8-378" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-379"><a href="#cb8-379" aria-hidden="true" tabindex="-1"></a>    <span class="co"># (C) Residual histogram</span></span>
<span id="cb8-380"><a href="#cb8-380" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].hist(std_residuals, bins<span class="op">=</span><span class="dv">25</span>, density<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb8-381"><a href="#cb8-381" aria-hidden="true" tabindex="-1"></a>                      color<span class="op">=</span>color, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb8-382"><a href="#cb8-382" aria-hidden="true" tabindex="-1"></a>    x_hist <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">200</span>)</span>
<span id="cb8-383"><a href="#cb8-383" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].plot(x_hist, stats.norm.pdf(x_hist), <span class="st">'k--'</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb8-384"><a href="#cb8-384" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].set_title(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> — Residual Distribution'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb8-385"><a href="#cb8-385" aria-hidden="true" tabindex="-1"></a>    axes[row, <span class="dv">2</span>].set_xlabel(<span class="st">'z-score'</span>)</span>
<span id="cb8-386"><a href="#cb8-386" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-387"><a href="#cb8-387" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Residual normality test</span></span>
<span id="cb8-388"><a href="#cb8-388" aria-hidden="true" tabindex="-1"></a>    sw_stat, sw_p <span class="op">=</span> stats.shapiro(std_residuals)</span>
<span id="cb8-389"><a href="#cb8-389" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> residuals: Shapiro-Wilk p = </span><span class="sc">{</span>sw_p<span class="sc">:.4f}</span><span class="ss">, mean = </span><span class="sc">{</span>std_residuals<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">, std = </span><span class="sc">{</span>std_residuals<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb8-390"><a href="#cb8-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-391"><a href="#cb8-391" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Figure 5: OU Model Diagnostic Plots'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, y<span class="op">=</span><span class="fl">1.01</span>)</span>
<span id="cb8-392"><a href="#cb8-392" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-393"><a href="#cb8-393" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../figures/fig5_ou_parameters.png'</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb8-394"><a href="#cb8-394" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-395"><a href="#cb8-395" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved: fig5_ou_parameters.png'</span>)</span>
<span id="cb8-396"><a href="#cb8-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-397"><a href="#cb8-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-398"><a href="#cb8-398" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretation — Model Diagnostics (Figure 5)</span></span>
<span id="cb8-399"><a href="#cb8-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-400"><a href="#cb8-400" aria-hidden="true" tabindex="-1"></a>The diagnostic plots assess whether the OU model adequately captures the dynamics of each spread series. For each currency, we examine three diagnostic plots:</span>
<span id="cb8-401"><a href="#cb8-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-402"><a href="#cb8-402" aria-hidden="true" tabindex="-1"></a>**Panel A — Standardized Residuals Over Time:**</span>
<span id="cb8-403"><a href="#cb8-403" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**USD:** Residuals appear **well-behaved** — scattered randomly around zero with most values between ±2 (the 95% band). No obvious pattern or trend is visible. A few exceedances of ±2 are expected in 155 observations (~5%, or ~8 points). This indicates the USD spread dynamics are **well-described** by the OU model.</span>
<span id="cb8-404"><a href="#cb8-404" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**KHR:** Residuals show a slight **clustering pattern** — larger residuals appear in the early sample (when the spread was compressing rapidly) and smaller residuals in the later sample. This suggests the model does not perfectly capture the **heteroskedastic** nature of KHR spread dynamics — volatility was higher in the compression phase. This motivates using time-varying parameters.</span>
<span id="cb8-405"><a href="#cb8-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-406"><a href="#cb8-406" aria-hidden="true" tabindex="-1"></a>**Panel B — Q-Q Plots:**</span>
<span id="cb8-407"><a href="#cb8-407" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**USD:** Points generally follow the 45° reference line, with minor deviations in both tails. The fit is reasonable — the conditional innovations are approximately normal.</span>
<span id="cb8-408"><a href="#cb8-408" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**KHR:** More visible deviation from the reference line, particularly in the **left tail** (the model underestimates the frequency of large negative innovations = sudden spread compressions). This is consistent with the structural break in the KHR series.</span>
<span id="cb8-409"><a href="#cb8-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-410"><a href="#cb8-410" aria-hidden="true" tabindex="-1"></a>**Panel C — Residual Histograms:**</span>
<span id="cb8-411"><a href="#cb8-411" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Both distributions are **roughly bell-shaped** and centered near zero, which is encouraging. The standardized residuals have standard deviation close to 1.0, confirming the model's variance estimate is correctly calibrated.</span>
<span id="cb8-412"><a href="#cb8-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-413"><a href="#cb8-413" aria-hidden="true" tabindex="-1"></a>**Overall Assessment:** The OU model is a **reasonable but imperfect** description of the data. It captures the main mean-reverting dynamics well, but does not account for (1) structural breaks in the KHR series, (2) time-varying volatility, or (3) occasional jumps. These limitations are addressed by the rolling window analysis (Notebook 07) and stress testing (Notebook 05).</span>
<span id="cb8-414"><a href="#cb8-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-415"><a href="#cb8-415" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-416"><a href="#cb8-416" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Save Parameters for Downstream Notebooks</span></span>
<span id="cb8-417"><a href="#cb8-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-420"><a href="#cb8-420" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb8-421"><a href="#cb8-421" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── Save Parameters ─────────────────────────────────────────────────────────</span></span>
<span id="cb8-422"><a href="#cb8-422" aria-hidden="true" tabindex="-1"></a>param_export <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-423"><a href="#cb8-423" aria-hidden="true" tabindex="-1"></a>    <span class="st">'parameter'</span>: [<span class="st">'kappa'</span>, <span class="st">'theta'</span>, <span class="st">'sigma'</span>, <span class="st">'se_kappa'</span>, <span class="st">'se_theta'</span>, <span class="st">'se_sigma'</span>,</span>
<span id="cb8-424"><a href="#cb8-424" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'half_life_months'</span>, <span class="st">'log_likelihood'</span>],</span>
<span id="cb8-425"><a href="#cb8-425" aria-hidden="true" tabindex="-1"></a>    <span class="st">'USD'</span>: [mle_usd[<span class="st">'kappa'</span>], mle_usd[<span class="st">'theta'</span>], mle_usd[<span class="st">'sigma'</span>],</span>
<span id="cb8-426"><a href="#cb8-426" aria-hidden="true" tabindex="-1"></a>            mle_usd[<span class="st">'se_kappa'</span>], mle_usd[<span class="st">'se_theta'</span>], mle_usd[<span class="st">'se_sigma'</span>],</span>
<span id="cb8-427"><a href="#cb8-427" aria-hidden="true" tabindex="-1"></a>            mle_usd[<span class="st">'half_life_months'</span>], mle_usd[<span class="st">'log_likelihood'</span>]],</span>
<span id="cb8-428"><a href="#cb8-428" aria-hidden="true" tabindex="-1"></a>    <span class="st">'KHR'</span>: [mle_khr[<span class="st">'kappa'</span>], mle_khr[<span class="st">'theta'</span>], mle_khr[<span class="st">'sigma'</span>],</span>
<span id="cb8-429"><a href="#cb8-429" aria-hidden="true" tabindex="-1"></a>            mle_khr[<span class="st">'se_kappa'</span>], mle_khr[<span class="st">'se_theta'</span>], mle_khr[<span class="st">'se_sigma'</span>],</span>
<span id="cb8-430"><a href="#cb8-430" aria-hidden="true" tabindex="-1"></a>            mle_khr[<span class="st">'half_life_months'</span>], mle_khr[<span class="st">'log_likelihood'</span>]]</span>
<span id="cb8-431"><a href="#cb8-431" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-432"><a href="#cb8-432" aria-hidden="true" tabindex="-1"></a>param_export.to_csv(<span class="st">'../data/processed/ou_parameters_mle.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-433"><a href="#cb8-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-434"><a href="#cb8-434" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">═══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-435"><a href="#cb8-435" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'       Parameters saved to ou_parameters_mle.csv'</span>)</span>
<span id="cb8-436"><a href="#cb8-436" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-437"><a href="#cb8-437" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(param_export.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb8-438"><a href="#cb8-438" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'═══════════════════════════════════════════════════════════'</span>)</span>
<span id="cb8-439"><a href="#cb8-439" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb8-440"><a href="#cb8-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-441"><a href="#cb8-441" aria-hidden="true" tabindex="-1"></a>***</span>
<span id="cb8-442"><a href="#cb8-442" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary of Key Findings</span></span>
<span id="cb8-443"><a href="#cb8-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-444"><a href="#cb8-444" aria-hidden="true" tabindex="-1"></a>The parameter estimation reveals that Cambodia's dual-currency spreads follow **qualitatively different** mean-reverting processes:</span>
<span id="cb8-445"><a href="#cb8-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-446"><a href="#cb8-446" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> USD <span class="pp">|</span> KHR <span class="pp">|</span></span>
<span id="cb8-447"><a href="#cb8-447" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb8-448"><a href="#cb8-448" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Speed** <span class="pp">|</span> Fast (κ = 1.85, half-life = 4.5 months) <span class="pp">|</span> Slow (κ = 0.46, half-life = 18 months) <span class="pp">|</span></span>
<span id="cb8-449"><a href="#cb8-449" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Equilibrium** <span class="pp">|</span> θ = 6.44%, precisely estimated <span class="pp">|</span> θ = 8.07%, imprecisely estimated due to structural break <span class="pp">|</span></span>
<span id="cb8-450"><a href="#cb8-450" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Volatility** | σ = 3.66, moderate | σ = 6.18, **1.7× higher** <span class="pp">|</span></span>
<span id="cb8-451"><a href="#cb8-451" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Stationary variance** | σ²/2κ = 3.6 | σ²/2κ = 41.5 (**11.5× higher**) <span class="pp">|</span></span>
<span id="cb8-452"><a href="#cb8-452" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Model fit** <span class="pp">|</span> Good — residuals well-behaved <span class="pp">|</span> Adequate — some heteroskedasticity <span class="pp">|</span></span>
<span id="cb8-453"><a href="#cb8-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-454"><a href="#cb8-454" aria-hidden="true" tabindex="-1"></a>**Core Implication:** The KHR segment combines **higher volatility** with **slower mean reversion**, creating a risk profile that is fundamentally more dangerous than the USD segment. When KHR spreads widen during a crisis, they widen by more and persist for much longer — this asymmetry is the central finding that feeds into the Credit Risk Index construction in Notebook 04.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>